test/workers:
  stage: test
  tags:
    - nodejs
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  dependencies:
    - global-install
  script:
    - cd fc-workers
    - yarn test
