npm-install:
  stage: build
  image: node:8
  script:
    - cd fc-exploitation
    - npm ci
  artifacts:
    paths:
      - fc-exploitation/node_modules

test:
  stage: test
  image: node:8
  dependencies:
    - npm-install
  script:
    - cd fc-exploitation
    - npm test
