test/exploitation:
  stage: test
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  tags:
    - nodejs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"' 
  needs:
    - job: global-install
      artifacts: true
  script:
    - cd fc-exploitation
    - yarn test

cypress/exploitation:
  stage: e2e
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"' 
  tags:
    - docker
  variables:
    FC_ROOT : "$CI_BUILDS_DIR/france-connect"
    TZ: "Europe/Paris"
  before_script:
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc-docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - rm -rf $FC_ROOT/fc-docker
    - git clone --single-branch -b $FC_DOCKER_VERSION https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-docker.git $FC_ROOT/fc-docker
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc-docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc-docker/volumes/src/fc-apps
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do ln -s $mock $FC_ROOT/fc-docker/volumes/src; done
  script:
    - docker-stack up fc-exploitation rnipp
    - docker-stack fixtures fc-exploitation
    - docker-stack run-prod csmr-hsm-prod
    - docker-stack start fc-exploitation rnipp
    - timeout 100 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://fc-exploitation.docker.dev-franceconnect.fr/login)" != "200" ]];
        do echo "Waiting for fc-exploitation..." && sleep 10; done' ||
        (echo 'Cannot connect to fc-exploitation' && exit 1)
    - npx cypress${CYPRESS_VERSION:=@5.6.0} run -c video=${CYPRESS_VIDEO} -P fc-exploitation/ || (
        (docker cp fc_fc-exploitation_1:/tmp/.pm2/logs fc-exploitation/cypress || true) &&
        (docker cp fc-rp-all:/var/log/nginx fc-exploitation/cypress/logs || true) &&
        exit 1)
  interruptible: true
  needs:
    - job: global-install
      artifacts: true
  artifacts:
    expire_in: 1 hrs
    when: on_failure
    paths:
    - fc-exploitation/cypress/screenshots
    - fc-exploitation/cypress/videos
    - fc-exploitation/cypress/logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc-docker/docker-stack halt
    - docker container prune -f && docker volume prune -f
