test(fc-exploitation):
  stage: test
  image: node:8
  dependencies:
    - global-install
  script:
    - cd fc-exploitation
    - npm test

database-test(fc-exploitation):
  stage: test
  image: node:8
  dependencies:
    - global-install
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: fc-exploitation
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: yolo
    DB_TYPE: postgres
    DB_DATABASE: fc-exploitation
    DB_HOST: postgres
    DB_USER: runner
    DB_PASSWORD: yolo
  script:
    - cd fc-exploitation
    - npm run migrations:run
    - npm run fixtures:load
