test/exploitation:
  stage: test
  image: node:12.15.0
  dependencies:
    - global-install
  script:
    - cd fc-exploitation
    - yarn test

run/exploitation:
  stage: run
  image: node:12.15.0
  dependencies:
    - global-install
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: fc-exploitation
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: yolo
    DB_TYPE: postgres
    DB_DATABASE: fc-exploitation
    DB_HOST: postgres
    DB_USER: runner
    DB_PASSWORD: yolo
  script:
    - cd fc-exploitation
    - yarn migrations:run
    - yarn fixtures:load
    - yarn build
