build(fc-exploitation):
  stage: build
  image: node:8
  script:
    - cd fc-exploitation
    - npm i
    - cd ../shared
    - npm i
  artifacts:
    paths:
      - fc-exploitation/node_modules
      - shared/node_modules

test(fc-exploitation):
  stage: test
  image: node:8
  dependencies:
    - build(fc-exploitation)
  script:
    - cd fc-exploitation
    - npm test
