test/exploitation:
  stage: test
  image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
  tags:
    - node
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  cache:
    key: '${CACHE_KEY}'
    policy: pull
    paths:
      - node_modules
      - fc-exploitation/node_modules
      - fc-support/node_modules
      - fc-workers/node_modules
      - shared/node_modules
  needs:
    - job: global-install
  script:
    - cd fc-exploitation
    - yarn install
    - yarn test

cypress/exploitation:
  timeout: 60 mins
  stage: e2e
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  tags:
    - cypress
  variables:
    TZ: 'Europe/Paris'
  cache:
    key: '${CACHE_KEY}'
    policy: pull
    paths:
      - node_modules
      - fc-exploitation/node_modules
      - fc-support/node_modules
      - fc-workers/node_modules
      - shared/node_modules
  before_script:
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
    - echo "FC_DOCKER_VERSION=$FC_DOCKER_VERSION"
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - rm -rf $FC_ROOT/fc
    - git clone --single-branch -b $FC_DOCKER_VERSION https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc.git $FC_ROOT/fc
    - cd $FC_ROOT/fc/docker/volumes/src && ln -s $FC_ROOT/fc fc
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc-apps
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do cd $mock && git fetch && git checkout -f origin/master && git clean -df && echo "Installing depedencies for $(/usr/bin/basename $mock)" && npm install; ln -sfn $mock $FC_ROOT/fc/docker/volumes/src; done
    - cd $CI_PROJECT_DIR
    - yarn install
  script:
    - VERBOSE=1 docker-stack up fc-exploitation
    - docker-stack start-all
    - docker-stack wait "fc-exploitation" "https://fc-exploitation.docker.dev-franceconnect.fr/login" "240"
    - yarn test:e2e:exploitation -c video=${CYPRESS_VIDEO} || (
      mkdir -p fc-exploitation/cypress/logs &&
      (docker cp fc_fc-exploitation_1:/tmp/.pm2/logs fc-exploitation/cypress/logs/fc-exploitation || true) &&
      (docker cp fc_csmr-hsm_1:/tmp/.pm2/logs fc-exploitation/cypress/logs/csmr-hsm || true) &&
      (docker cp fc_csmr-user-preferences-high_1:/tmp/.pm2/logs fc-exploitation/cypress/logs/csmr-user-preferences-high || true) &&
      (docker cp fc-rp-all:/var/log/nginx fc-exploitation/cypress/logs || true) &&
      exit 1)
  interruptible: true
  needs:
    - job: global-install
  artifacts:
    expire_in: 1 hrs
    when: on_failure
    paths:
      - fc-exploitation/cypress/screenshots
      - fc-exploitation/cypress/videos
      - fc-exploitation/cypress/logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune -f && docker volume prune -f
