export enum ErrorCode {
  NO_IDP = 1,
  INVALID_IDENTITY = 6,
  AGENT_NOT_FOUND = 15,
  DISABLED_PROVIDER = 17,
  ACR_NOT_SATISFIED = 20,
  LOGIN_REQUIRED = 21,
  BLOCKED_ACCOUNT = 24,
  UNAUTHORIZED_EMAIL = 25,
  NO_IDP_SIRET = 26,
}
