// == FI
const fip = [
  {
    uid: '8dfc4080-c90d-4234-969b-f6c961de3e90',
    name: 'fip1',
    active: true,
    display: true,
    title: 'Identity Provider - eIDAS élevé',
    image: 'fi-eidas-3.png',
    imageFocus: 'demonstration_eleve_hover.png',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84b31943',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 1,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },

  //FIP2
  {
    uid: '07e573f2-3312-4bb9-bc48-6fcec737e497',
    name: 'fip2',
    active: true,
    display: true,
    title: 'Identity Provider - eIDAS faible',
    image: 'fi-eidas-1.png',
    imageFocus: 'fi-eidas-1.png',
    alt: '',
    eidas: 1,
    mailto: '',
    specificText: 'specific text fip2',
    url: 'https://fip2.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip2.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fip2.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip2.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip2.docker.dev-franceconnect.fr/api/user',
    endSessionURL: 'https://fip2.docker.dev-franceconnect.fr/user/session/end',
    discoveryUrl:
      'https://fip2.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84b',
    client_secret:
      '9SUcAHqnwkaLQdDCUPKvb1O4Tfrjxu4h2zUC54SZedXy9/GnkNRYSdFeQkN0x3pF+17u22DPIRC0ZeSYi0cdBsieSw==',
    order: 2,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: false,
    betaText: '',
  },

  //FIP3
  {
    uid: 'b5e9539a-599a-4ed2-9b4f-8f4bfc5fbb64',
    name: 'fip3',
    active: true,
    display: true,
    title: 'Identity Provider - eIDAS substantiel',
    image: 'fi-eidas-2.png',
    imageFocus: 'fi-eidas-2.png',
    alt: '',
    eidas: 2,
    mailto: '',
    specificText: 'specific text fip3',
    url: 'https://fip3.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip3.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fip3.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip3.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip3.docker.dev-franceconnect.fr/api/user',
    endSessionURL: 'https://fip3.docker.dev-franceconnect.fr/user/session/end',
    discoveryUrl:
      'https://fip3.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84c',
    client_secret:
      'w9d+Kp/kD5BONBf1NW70Oy4keuS3bNdpXjqX9Lb7vvW9UqvWhRSYh7nONkI8OAMzMyl9B3GafLQzXWflaWn8Sc0C4w==',
    order: 3,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: false,
    betaText: '',
  },

  //Aidants Connect mock
  {
    uid: '3189d655-0c78-4ff7-9758-f3a3ac36dd7e',
    name: 'aidants-connect-mock',
    active: true,
    display: true,
    title: 'Aidants Connect mock',
    image: 'fi-aidantsconnect.png',
    imageFocus: 'fi-aidantsconnect.png',
    alt: 'aidants connect mock',
    trustedIdentity: 'false',
    eidas: 1,
    mailto: 'test@dev-franceconnect.fr',
    specificText: 'aidants connect mock',
    url: 'https://aidants-connect-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://aidants-connect-mock.docker.dev-franceconnect.fr/',
    jwksURL: 'https://aidants-connect-mock.docker.dev-franceconnect.fr/not-use',
    authzURL:
      'https://aidants-connect-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL:
      'https://aidants-connect-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL:
      'https://aidants-connect-mock.docker.dev-franceconnect.fr/api/user',
    endSessionURL:
      'https://aidants-connect-mock.docker.dev-franceconnect.fr/user/session/end',
    discoveryUrl: '',
    discovery: false,
    clientID: '08a1a257648c1742c74d6a3d84b31943',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: null,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    isBeta: false,
    betaText: '',
  },

  // eIDAS Bridge as Identity Provider
  {
    uid: '1f4d6633-d853-43c6-b461-ce54fdc19bff',
    name: 'eidas_interconnection_bridge',
    active: true,
    display: true,
    title: 'eIDAS Bridge',
    image: '',
    imageFocus: '',
    alt: 'eIDAS Bridge',
    eidas: 2,
    mailto: '',
    specificText: 'specific text eidas bridge',
    url: 'https://bridge.eidas.docker.dev-franceconnect.fr',
    statusURL:
      'https://bridge.eidas.docker.dev-franceconnect.fr/api/v1/oidc/provider/me',
    authzURL:
      'https://bridge.eidas.docker.dev-franceconnect.fr/api/v1/oidc/provider/auth',
    tokenURL:
      'https://bridge.eidas.docker.dev-franceconnect.fr/api/v1/oidc/provider/token',
    userInfoURL:
      'https://bridge.eidas.docker.dev-franceconnect.fr/api/v1/oidc/provider/me',
    discoveryUrl:
      'https://bridge.eidas.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: 'ObnxTzt6NzRXbPmbhrVx175jyQ9B6iwW',
    client_secret:
      'ImUyBBXcWVg0Z/nq0RSmm9nlBbTIvaE2cJU9005a9gu88wOGA4gB6HQPQhxsKyTXJAnG+rmvfLG/suLI',
    order: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    isBeta: false,
    betaText: '',
  },

  //FIP1 Désactivé
  {
    uid: '375096dc-a1f3-4965-83f0-fea99e8e29b8',
    name: 'fip1_deactivated',
    active: false,
    display: true,
    hoverMsg: 'Identity Provider - Désactivé',
    title: 'Identity Provider - Désactivé',
    image: 'fi-eidas-3.png',
    imageFocus: 'fi-eidas-3.png',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '0cce65126ab9dc34fedd4273bfefe11b',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 5,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },

  //FIP1 Blacklisté
  {
    uid: '6876d80b-13cf-490a-af28-2b947a1b2fa7',
    name: 'fip1_blacklisted_by_fsp2',
    active: true,
    display: true,
    title: 'Identity Provider - Blacklisté par FSP2',
    image: '',
    imageFocus: '',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '54526d8a5b77bb70cb8280ff8ca735fa',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 6,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },

  //FIP1 Whitelisté
  {
    uid: '5fe184bc-92d2-4718-b7db-30673c67adf7',
    name: 'fip1_not_whitelisted_by_fsp3',
    active: true,
    display: true,
    title: 'Identity Provider - Non Whitelisté par FSP3',
    image: '',
    imageFocus: '',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '54526d8a5b77bb70cb8280ff8ca735fa',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 7,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },

  //FIP1 Non affiché
  {
    uid: '0adf04be-536e-4986-b639-73ea8d38493e',
    name: 'fip1_not_displayed',
    active: true,
    display: false,
    hoverMsg: 'Identity Provider - Non Affiché',
    title: 'Identity Provider - Non Affiché',
    image: '',
    imageFocus: '',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '0cce65126ab9dc34fedd4273bfefe11b',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: null,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },
  {
    uid: 'c88c1574-b97c-473d-8be8-96d55aa001e5',
    name: 'fip1_not_displayed_and_deactivated',
    active: false,
    display: false,
    hoverMsg: 'Identity Provider - Non Affiché et Désactivé',
    title: 'Identity Provider - Non Affiché et Désactivé',
    image: '',
    imageFocus: '',
    alt: 'impots',
    eidas: 3,
    mailto: '',
    specificText: 'specific text fip1',
    url: 'https://fip1.docker.dev-franceconnect.fr/',
    statusURL: 'https://fip1.docker.dev-franceconnect.fr/',
    authzURL: 'https://fip1.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fip1.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fip1.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fip1.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '0cce65126ab9dc34fedd4273bfefe11b',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: null,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    endSessionURL: 'https://fsp1.docker.dev-franceconnect.fr/user/session/end',
    isBeta: false,
    betaText: '',
  },

  {
    uid: 'b18cb985-9492-4737-9890-da69a87a012a',
    name: 'fib_act_vis_blacklisted',
    active: true,
    display: true,
    title: 'Beta Identity Provider - Blacklisté par FSP2',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 1,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta-mock.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 8,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - Blacklisté par FSP2",
  },

  {
    uid: 'caf0fe8d-0d8b-4288-9850-ce8b2a4b5251',
    name: 'fib_act_vis',
    active: true,
    display: true,
    title: 'Beta Identity Provider - eIDAS faible',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 1,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta-mock.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 9,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - eIDAS faible",
  },

  {
    uid: '0c1edaa3-c0a5-4cac-902e-29872bae2c6e',
    name: 'fib_act_vis2',
    active: true,
    display: true,
    title: 'Beta Identity Provider - eIDAS substantiel',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 2,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta-mock.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 10,
    endSessionURL: 'https://fsp2.docker.dev-franceconnect.fr/user/session/end',
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - eIDAS substantiel",
  },

  {
    uid: '77fe5e8c-364c-440e-909f-5ef4f494e170',
    name: 'fib_desact_vis',
    active: false,
    display: true,
    title: 'Beta Identity Provider - Désactivé',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 1,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta-mock.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 11,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - Désactivé",
  },

  {
    uid: '419c0c21-7607-464a-8ecd-07eb1517f484',
    name: 'fib_act_invis',
    active: true,
    display: false,
    title: 'Beta Identity Provider - Invisible',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 2,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: null,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - Invisible",
  },

  {
    uid: 'caf0fe8d-0d8b-4288-9850-ce8b2a4b5252',
    name: 'fib_act_vis_whitelisted',
    active: true,
    display: true,
    title: 'Beta Identity Provider - Whitelisté par FSP3',
    image: '',
    imageFocus: '',
    alt: '',
    eidas: 1,
    mailto: '',
    specificText: 'specific text fi beta',
    url: 'https://fi-beta-mock.docker.dev-franceconnect.fr/',
    statusURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/status',
    authzURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/authorize',
    tokenURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/user/token',
    userInfoURL: 'https://fi-beta-mock.docker.dev-franceconnect.fr/api/user',
    discoveryUrl:
      'https://fi-beta-mock.docker.dev-franceconnect.fr/.well-known/openid-configuration',
    discovery: true,
    clientID: '09a1a257648c1742c74d6a3d84m',
    client_secret:
      '+3wLzOoeALg6COG66XCPQNxxiH3jYNzEOxLGWOyaiI/PLYDY5xp7KlNMgJNYPhTQSa1kKFcqg5G5SnOK',
    order: 12,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: '5cd955c4ee275cd32522dc07',
    isBeta: true,
    betaText: "Fournisseur d'identité béta - Whitelisté par FSP3",
  },
];

// -- FIs ----------

fip.forEach((fi) => {
  print(`FIP > Initializing provider: ${fi.name} - Activated`);
  db.provider.update({ uid: fi.uid }, fi, { upsert: true });
});
