// == FS
const fsp = {
  fsp1: {
    name: 'Service Provider Example',
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/login-callback',
      'https://fsp1.docker.dev-franceconnect.fr/data-callback',
      'https://fsp1.docker.dev-franceconnect.fr/tracks-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/logout-callback',
    ],
    key: 'a0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc',
    client_secret:
      'tbjUBu7gwf317yIjPRlo7zk89LAPOUzWhDzodO1sh0jAqudu6BxI37NqkzGdR8DfHT9mgt6+ZgpLZ8OU8HZHT/OXRcZrssIbpYzoiale4dEmYOnDmBcwbwJhzjQ=',
    credentialsFlow: false,
    email: 'fsp1@franceconnect.loc',
    logo: 'logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png',
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: true,
    type: 'public',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'idp_birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'email',
      'preferred_username',
      'address',
      'phone',
      'idp_id',
      'dgfip_rfr',
      'dgfip_nbpart',
      'dgfip_sitfam',
      'dgfip_pac',
      'dgfip_aft',
      'cnam_paiements_ij',
      'connexion_tracks',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
  },

  fsp2: {
    name: 'Virtual Private Service Provider for Scopes',
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp2.docker.dev-franceconnect.fr/login-callback',
      'https://fsp2.docker.dev-franceconnect.fr/data-callback',
      'https://fsp2.docker.dev-franceconnect.fr/tracks-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp2.docker.dev-franceconnect.fr/logout-callback',
    ],
    key: '7a79e45107f9ccc6a3a5971d501220dc4fd9e87bb5e3fc62ce4104c756e22775',
    client_secret:
      'bbg3e0zidcMLRFF7MPOUIgyOYQo2fkVR7xYLtLAEUiWGQBcXhg8X0/+K0ZXGipk/Cr4oZTYqL5MRN4y5v16MUFjFnvGffCzrn3M3w2voQhDzq8Ggj/gorS1hYhY=',
    credentialsFlow: false,
    email: 'fsp2@franceconnect.loc',
    logo: 'logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png',
    IPServerAddressesAndRanges: ['2.2.2.2'],
    active: true,
    type: 'private',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    blacklistByIdentityProviderActivated: true,
    blacklistByIdentityProvider: {
      fip1_blacklisted_by_fsp2: true,
      fib_act_vis_blacklisted: true,
    },
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'dgfip_rfr',
      'dgfip_nbpart',
      'dgfip_sitfam',
      'dgfip_pac',
      'dgfip_aft',
      'cnam_paiements_ij',
      'connexion_tracks',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
  },

  fsp3: {
    name: 'Virtual Private Service Provider for Consent',
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp3.docker.dev-franceconnect.fr/login-callback',
      'https://fsp3.docker.dev-franceconnect.fr/data-callback',
      'https://fsp3.docker.dev-franceconnect.fr/tracks-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp3.docker.dev-franceconnect.fr/logout-callback',
    ],
    key: '6495f347513b860e6b931fae4a1ba70c8489a558a0fc74ecdc094d48a4035e77',
    client_secret:
      'cjOdm1/StyiLtVPEOL0iynWw7lioAtv5/ShUCjNZZ5MPH3hrEosTgTC6VuZfCOu/R6Yw3NjmI2aD4Bi4p6A8JXKNC/hFrV37BstiuzGbjEDvFlLzhKNpOZCz4Kw=',
    credentialsFlow: false,
    email: 'fsp3@franceconnect.loc',
    logo: 'logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png',
    IPServerAddressesAndRanges: ['2.2.2.2'],
    active: true,
    type: 'private',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    whitelistByServiceProviderActivated: true,
    whitelistByIdentityProvider: {
      fip1: true,
      fip2: true,
      fip3: true,
      eidas_interconnection_bridge: true,
      fib_act_vis_whitelisted: true,
    },
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'preferred_username',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'dgfip_rfr',
      'dgfip_nbpart',
      'dgfip_sitfam',
      'dgfip_pac',
      'dgfip_aft',
      'cnam_paiements_ij',
      'mi_siv_carte_grise',
      'mesri_identifiant',
      'cnous_statut_boursier',
      'api_fc-liste-paiementsv1',
      'connexion_tracks',
    ],
    identityConsent: true,
    trustedIdentity: false,
    eidas: 1,
  },

  users: {
    name: 'Site Usagers',
    site: 'https://site.com',
    redirect_uris: [
      'https://fcp.docker.dev-franceconnect.fr/traces/login-callback',
    ],
    post_logout_redirect_uris: [
      'https://fcp.docker.dev-franceconnect.fr/traces/logout-callback',
    ],
    key: '6925fb8143c76eded44d32b40c0cb1006065f7f003de52712b78985704f39950',
    client_secret:
      'gUIMFjNo6pOKBBhPKPBRE0lTPIUo9mxcedLFtj90sTJVkOHjOJ42UB3c9Xbc7WI3N6jmJVFCMIU49IqE+6Z48rqP1ekczyZ3viEkfZDMZpaOc66MNQvyERC/lSU=',
    credentialsFlow: false,
    email: 'users@franceconnect.loc',
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: true,
    type: 'public',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'email',
      'preferred_username',
      'address',
      'phone',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
  },

  'FS désactivé': {
    name: 'FS désactivé',
    site: 'https://site.com',
    redirect_uris: [
      'https://fcp.docker.dev-franceconnect.fr/traces/login-callback',
    ],
    post_logout_redirect_uris: [
      'https://fcp.docker.dev-franceconnect.fr/traces/logout-callback',
    ],
    key: 'fs-desactive',
    client_secret:
      'gUIMFjNo6pOKBBhPKPBRE0lTPIUo9mxcedLFtj90sTJVkOHjOJ42UB3c9Xbc7WI3N6jmJVFCMIU49IqE+6Z48rqP1ekczyZ3viEkfZDMZpaOc66MNQvyERC/lSU=',
    credentialsFlow: false,
    email: 'users@franceconnect.loc',
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: false,
    type: 'public',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'email',
      'preferred_username',
      'address',
      'phone',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
  },

  fsStats: {
    name: 'FsStats',
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp2.docker.dev-franceconnect.fr/login-callback',
      'https://fsp2.docker.dev-franceconnect.fr/data-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp2.docker.dev-franceconnect.fr/logout-callback',
    ],
    key: '28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a68',
    client_secret:
      'bbg3e0zidcMLRFF7MPOUIgyOYQo2fkVR7xYLtLAEUiWGQBcXhg8X0/+K0ZXGipk/Cr4oZTYqL5MRN4y5v16MUFjFnvGffCzrn3M3w2voQhDzq8Ggj/gorS1hYhY=',
    credentialsFlow: false,
    email: 'stats@stats.fr',
    logo: 'logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png',
    IPServerAddressesAndRanges: ['2.2.2.2'],
    active: true,
    type: 'private',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    blacklistByIdentityProviderActivated: true,
    blacklistByIdentityProvider: {
      fip1_blacklisted_by_fsp2: true,
    },
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'dgfip_rfr',
      'dgfip_nbpart',
      'dgfip_sitfam',
      'dgfip_pac',
      'dgfip_aft',
      'cnam_paiements_ij',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,

    production_key:
      '28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a68',
    whitelistByServiceProviderActivated: false,
  },
  'user dashboard': {
    name: 'User Dashboard',
    site: 'https://site.com',
    redirect_uris: [
      'https://ud.docker.dev-franceconnect.fr/api/oidc-callback/envIssuer',
    ],
    post_logout_redirect_uris: [
      'https://ud.docker.dev-franceconnect.fr/api/logout-callback',
    ],
    key: 'myclientidforud-back-with-so-many-characters',
    client_secret:
      'g73pC+HYNhr2VAleGDjXo/lXHlyltxq1PavSDdoCzFC72Shd86S1e+0ch6riozdKRrIw8ax3b1ChPISIGrs9GTinFbEUXgH86/z0fppT2T+p/A7aw0msBq7Rf+8=',
    credentialsFlow: false,
    email: 'users@franceconnect.loc',
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: true,
    type: 'public',
    __v: 4,
    updatedAt: '2019-04-24 17:09:17',
    updatedBy: 'admin',
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'email',
      'idp_id',
    ],
    identityConsent: false,
    id_token_signed_response_alg: 'ES256',
    id_token_encrypted_response_alg: 'RSA-OAEP',
    id_token_encrypted_response_enc: 'A256GCM',
    userinfo_signed_response_alg: 'ES256',
    userinfo_encrypted_response_alg: 'RSA-OAEP',
    userinfo_encrypted_response_enc: 'A256GCM',
    jwks_uri: 'https://ud.docker.dev-franceconnect.fr/.well-known/keys',
    trustedIdentity: false,
    eidas: 1,
  },

  MarieDeHem: {
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/login-callback',
      'https://fsp1.docker.dev-franceconnect.fr/data-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/logout-callback',
    ],
    updatedAt: '2019-05-22T14:36:12.516Z',
    key: '28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a95',
    client_secret:
      '4eQRa1ab1h8jIKVs53cW8FBUGIa5KQLlXQpdP/lGe3EJifIwUMHR0w6HKxu3ccGzR0y6+aS2wLAifrmhsT76TtVCvnNQAF5rONzLejQ7Hqy1LBF8TAUpx+8yFak=',
    signup_id: '1234567890',
    name: 'Marie de HEM',
    email: 'test@test.fr',
    contacts: [],
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: true,
    type: 'public',
    secretCreatedAt: '2019-05-22T14:36:12.494Z',
    createdAt: '2019-05-22T14:36:12.493Z',
    credentialsFlow: false,
    scopes: [
      'openid',
      'given_name',
      'family_name',
      'birthdate',
      'gender',
      'birthplace',
      'birthcountry',
      'email',
      'dgfip_rfr',
      'dgfip_nbpart',
      'dgfip_sitfam',
      'dgfip_pac',
      'dgfip_aft',
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    __v: 0,
  },

  // new service pour tester les scopes
  Test_update_old_service_provider: {
    site: 'https://site.com',
    redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/login-callback',
      'https://fsp1.docker.dev-franceconnect.fr/data-callback',
    ],
    post_logout_redirect_uris: [
      'https://fsp1.docker.dev-franceconnect.fr/logout-callback',
    ],
    updatedAt: '2019-05-22T14:36:12.516Z',
    key: '64e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c288d28a67',
    client_secret:
      'EKMIJqIjjo0L7TmRJcdJj4QcmxMw5dLYkw20c949ezSI37tM51A2yzopBAJL+EFo5k717uIv/Ayb+hgsGu2P5Bntaa1ch+Z8QwaN5QgagJQfjMpUqqY5OUhXRHE=',
    signup_id: '14567890123',
    name: 'Test_update_old_service_provider',
    email: 'test@test.fr',
    contacts: [],
    IPServerAddressesAndRanges: ['1.1.1.1'],
    active: true,
    type: 'public',
    secretCreatedAt: '2019-05-22T14:36:12.494Z',
    createdAt: '2019-05-22T14:36:12.493Z',
    credentialsFlow: false,
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    __v: 0,
  },
};

/* ------------------------------------------------------------------------------- */
Object.values(fsp).forEach((fs) => {
  print(`${fs.name} > Initializing provider: ${fs.name}`);
  db.client.update({ name: fs.name }, fs, { upsert: true });
});
