import {
  Controller,
  Get,
  Res,
  Body,
  Post,
  Inject,
  ValidationPipe,
  UsePipes,
} from '@nestjs/common';
import { ISessionGenericService, Session } from '@fc/session-generic';
import { OidcClientSession } from './dto';
import { IDENTITY_PROVIDER_SERVICE } from './tokens';
import { IIdentityProviderAdapter } from './interfaces';
import { RedirectToIdp } from './dto';
import { OidcClientRoutes } from './enums';
import { OidcClientService } from './services';

/**
 * @TODO #446 This service provider should not be generic, When it's called with FC
 * we have the spId in session but not when it's called with a service provder
 * @see https://gitlab.dev-franceconnect.fr/france-connect/fc/-/issues/446
 */

@Controller()
export class OidcClientController {
  // Dependency injection can require more than 4 parameters
  /* eslint-disable-next-line max-params */
  constructor(
    private readonly oidcClient: OidcClientService,
    @Inject(IDENTITY_PROVIDER_SERVICE)
    private readonly identityProvider: IIdentityProviderAdapter,
  ) {}
  /**
   * @todo #242 get configured parameters (scope and acr)
   */
  @Post(OidcClientRoutes.REDIRECT_TO_IDP)
  @UsePipes(new ValidationPipe({ whitelist: true }))
  async redirectToIdp(
    @Res() res,
    @Body() body: RedirectToIdp,
    /**
     * @todo Adaptation for now, correspond to the oidc-provider side.
     * Named "OidcClient" because we need a future shared session between our libs oidc-provider and oidc-client
     * without a direct dependance like now.
     * @author Hugues
     * @date 2021-04-16
     * @ticket FC-xxx
     */
    @Session('OidcClient')
    sessionOidc: ISessionGenericService<OidcClientSession>,
  ): Promise<void> {
    const {
      scope,
      claims,
      providerUid,
      // acr_values is an oidc defined variable name
      // eslint-disable-next-line @typescript-eslint/naming-convention
      acr_values,
    } = body;

    let serviceProviderId: string | null;
    try {
      const { spId } = await sessionOidc.get();
      serviceProviderId = spId;
    } catch (error) {
      serviceProviderId = null;
    }
    if (serviceProviderId) {
      await this.oidcClient.utils.checkIdpBlacklisted(
        serviceProviderId,
        providerUid,
      );
    }

    // TODO END
    const { state, nonce } =
      await this.oidcClient.utils.buildAuthorizeParameters();

    const authorizationUrl = await this.oidcClient.utils.getAuthorizeUrl({
      state,
      scope,
      providerUid,
      // acr_values is an oidc defined variable name
      // eslint-disable-next-line @typescript-eslint/naming-convention
      acr_values,
      nonce,
      claims,
    });

    const { name: idpName } = await this.identityProvider.getById(providerUid);

    await sessionOidc.set({
      idpId: providerUid,
      idpName,
      idpState: state,
      idpNonce: nonce,
    });

    res.redirect(authorizationUrl);
  }

  /**
   * @TODO #141 implement proper well-known
   * @see https://gitlab.dev-franceconnect.fr/france-connect/fc/-/issues/141
   *  - generated by openid-client
   *  - pub keys orverrided by keys from HSM
   */
  @Get(OidcClientRoutes.WELL_KNOWN_KEYS)
  async getWellKnownKeys() {
    return this.oidcClient.utils.wellKnownKeys();
  }
}
