import {
  Controller,
  Get,
  Param,
  Req,
  Res,
  Body,
  Post,
  Inject,
  ValidationPipe,
  UsePipes,
} from '@nestjs/common';
import { OidcClientService } from './services';
import { SessionService } from '@fc/session';
import { TrackingService } from '@fc/tracking';
import { AppConfig } from '@fc/app';
import { ConfigService } from '@fc/config';
import { IDENTITY_PROVIDER_SERVICE } from './tokens';
import { IIdentityProviderService } from './interfaces';
import { OidcClientTokenEvent, OidcClientUserinfoEvent } from './events';
import { RedirectToIdp, GetOidcCallback } from './dto';
import { OidcClientRoutes } from './enums';
@Controller()
export class OidcClientController {
  constructor(
    private readonly oidcClient: OidcClientService,
    private readonly session: SessionService,
    @Inject(IDENTITY_PROVIDER_SERVICE)
    private readonly identityProvider: IIdentityProviderService,
    private readonly tracking: TrackingService,
    private readonly config: ConfigService,
  ) {}

  /**
   * @todo #242 get configured parameters (scope and acr)
   */
  @Post(OidcClientRoutes.REDIRECT_TO_IDP)
  @UsePipes(new ValidationPipe({ whitelist: true }))
  async redirectToIdp(@Res() res, @Req() req, @Body() body: RedirectToIdp) {
    const {
      state,
      scope,
      providerUid,
      // acr_values is an oidc defined variable name
      // eslint-disable-next-line @typescript-eslint/naming-convention
      acr_values,
      nonce,
    } = await this.oidcClient.buildAuthorizeParameters(body);

    const authorizationUrl = await this.oidcClient.getAuthorizeUrl(
      state,
      scope,
      providerUid,
      // acr_values is an oidc defined variable name
      // eslint-disable-next-line @typescript-eslint/naming-convention
      acr_values,
      nonce,
    );

    const { name: idpName } = await this.identityProvider.getById(providerUid);

    await this.session.patch(req.fc.interactionId, {
      idpId: providerUid,
      idpName,
      idpState: state,
      idpNonce: nonce,
    });

    res.redirect(authorizationUrl);
  }

  /**
   * @TODO Handle caching `client` or passing it to the service
   * to avoid double discovery.
   *
   * Currently the two methods, `getTokenSet` and `getUserinfo`, each make their own call
   * to `getClient`, which, if enabled, queries the idp discovery url.
   *
   * This results in 2 additionals HTTP queries instead of one or zero (agressive caching)
   *
   * Note that this controller already has to perform 2 HTTP queries to idp (`/token` & `/userinfo`)
   */
  @Get(OidcClientRoutes.OIDC_CALLBACK)
  @UsePipes(new ValidationPipe({ whitelist: true }))
  async getOidcCallback(
    @Req() req,
    @Res() res,
    @Param() params: GetOidcCallback,
  ) {
    const { providerUid } = params;
    const uid = req.fc.interactionId;
    const { idpState, idpNonce } = await this.session.get(uid);

    // OIDC: call idp's /token endpoint
    const tokenSet = await this.oidcClient.getTokenSet(
      req,
      providerUid,
      idpState,
      idpNonce,
    );
    // openid defined property names
    // eslint-disable-next-line @typescript-eslint/naming-convention
    const { access_token: accessToken } = tokenSet;
    this.tracking.track(OidcClientTokenEvent, req);

    // OIDC: call idp's /userinfo endpoint
    const idpIdentity = await this.oidcClient.getUserInfo(
      accessToken,
      providerUid,
    );
    this.tracking.track(OidcClientUserinfoEvent, req);

    // BUSINESS: Locally store received identity
    const { acr } = tokenSet.claims();

    this.session.patch(uid, { idpIdentity, idpAcr: acr });

    // BUSINESS: Redirect to business page
    const { urlPrefix } = this.config.get<AppConfig>('App');
    res.redirect(`${urlPrefix}/interaction/${uid}/verify`);
  }

  /**
   * @TODO #141 implement proper well-known
   * @see https://gitlab.dev-franceconnect.fr/france-connect/fc/-/issues/141
   *  - generated by openid-client
   *  - pub keys orverrided by keys from HSM
   */
  @Get(OidcClientRoutes.WELL_KNOWN_KEYS)
  async getWellKnownKeys() {
    return this.oidcClient.wellKnownKeys();
  }
}
