#

fca_labeller:
  stage: Review
  needs: []
  image: alpine/curl
  variables:
    ALLOWED_PATHS: |
      back/apps/core-fca
      back/instances/core-fca-low
      quality/fca
      docker/compose/fca-low
      docker/volumes/fca-low
      docker/volumes/mongo-fca-low
    LABELS: "ProConnect:pas d'impact FC"
  before_script:
    - apk add --no-cache --upgrade git
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --depth 20
  script:
    - |
      curl \
        --data-urlencode "remove_labels=${LABELS}" \
        --fail \
        --header "PRIVATE-TOKEN: ${LABELLER_CI_API_TOKEN}" \
        --location \
        --request PUT \
        --show-error \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}"

    - CHANGED_FILES=$(git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA)
    - ALLOWED_PATTERN=$(printf "%s|" $ALLOWED_PATHS | sed 's/|$//')

    - |
      if echo "$CHANGED_FILES" | grep -v -E "^($ALLOWED_PATTERN)" >/dev/null; then
        echo "Changes detected outside the allowed paths. Job will not proceed."
        exit 0
      fi

    - |
      curl \
        --data-urlencode "add_labels=${LABELS}" \
        --fail \
        --header "PRIVATE-TOKEN: ${LABELLER_CI_API_TOKEN}" \
        --location \
        --request PUT \
        --show-error \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}"

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
