version: "3.4"

services:
  ####################
  # CORE FCP LOW
  ####################

  core-fcp-low:
    hostname: core-fcp-low
    image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "rnipp"
      - "mongo-fcp-low"
      - "redis-pwd"
      - "squid"
      - "haproxy"
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/client_certs:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/fcp-low/.env/core-fcp-low.env"
    ports:
      - 9300:9300
    tty: true
    networks:
      - public
      - public-fcp-low
      - data
    command: "pm2 logs"

networks:
  public-fcp-low:
