version: "3.4"

services:
  ####################
  # SP Mocks V2
  ####################

  fsp1-low:
    hostname: fsp1-low
    image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "redis-pwd"
      - "squid"
      - "haproxy"
    volumes:
      - "../volumes/src/fc/back:/var/www/app"
      - "../volumes/app:/opt/scripts"
      - "../volumes/log/:/var/log/app"
      - "../volumes/.home:/home"
      - "../volumes/ssl:/etc/ssl/client_certs:ro"
    env_file:
      - "./shared/.env/base-app.env"
      - "./fcp-low/.env/fsp1-low.env"
    ports:
      - 9301:9301
    tty: true
    networks:
      - public
      - public-fcp-low
      - data
    command: "pm2 logs"

  ####################
  # IDP Mocks V2
  ####################

  fip1-low:
    hostname: fip1-low
    image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "redis-pwd"
      - "squid"
      - "haproxy"
    volumes:
      - "../volumes/src/fc/back:/var/www/app"
      - "../volumes/app:/opt/scripts"
      - "../volumes/fcp-low/mocks/idp/databases:/var/databases"
      - "../volumes/log/:/var/log/app"
      - "../volumes/.home:/home"
      - "../volumes/ssl:/etc/ssl/client_certs:ro"
    env_file:
      - "./shared/.env/base-app.env"
      - "./fcp-low/.env/fip1-low.env"
    ports:
      - 9230:9230
    tty: true
    networks:
      - public
      - public-fcp-low
      - data
    command: "pm2 logs"