version: '3.4'

services:
  ####################
  # MINIMUM FCP LOW
  ####################

  min-fcp-low:
    image: alpine
    depends_on:
      - 'core-fcp-low'
      - 'fsp1-low'
      - 'fip1-low'

  ####################
  # ALL FCP LOW
  ####################

  all-fcp-low:
    image: alpine
    depends_on:
      - 'core-fcp-low'
      - 'fsp1-low'
      - 'fip1-low'
      - 'fip2-low'
      - 'fip3-low'
