version: "2.4"

services:
  ####################
  # MINIMUM FCP LOW
  ####################

  min-fcp-low:
    image: alpine
    depends_on:
      - "core-fcp-low"
      - "fsp1-low"
      - "fip1-low"

  ####################
  # BDD FCP LOW
  ####################

  bdd-fcp-low:
    image: alpine
    depends_on:
      - "core-fcp-low"
      # -- SP
      - "fsp1-low"
      - "fsp2-low"
      - "fsp3-low"
      - "fsp4-low"
      # -- IdP
      - "fip1-low"
      - "fip2-low"
      - "fip3-low"
      - "fip4-low"
      - "fip8-low"
      # --
      - "rnipp"

  ####################
  # ALL FCP LOW
  ####################

  all-fcp-low:
    image: alpine
    depends_on:
      - "core-fcp-low"
      - "fsp1-low"
      - "fsp2-low"
      - "fsp3-low"
      - "fsp4-low"
      - "fip1-low"
      - "fip2-low"
      - "fip3-low"
      - "fip4-low"
      - "fip8-low"
      # --
      - "maildev"
