include: '/back/.gitlab-build-template.yml'

partners-fca/back-build-image:
  extends: .base-build
  variables:
    APP: partners-fca
    MSG: "environments/nubo01-fca-integ/group_vars/all/versions.yml\nenvironments/nubo12-fca-integ/group_vars/all/versions.yml\npartners_back_version:"

partners-fca/back-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: partners-fca
    MSG: "environments/nubo01-fca-prod/group_vars/all/versions.yml\nenvironments/nubo12-fca-prod/group_vars/all/versions.yml\npartners_back_version:"
  needs:
    - job: partners-fca/back-build-image
