import { TrackedEvent } from '../enums';

export const trackedEventSteps: Record<TrackedEvent, string> = {
  FC_AUTHORIZE_INITIATED: '1.0.0',
  FC_SSO_INITIATED: '1.1.0',
  SP_DISABLED_SSO: '1.2.0',
  FC_SHOWED_IDP_CHOICE: '2.0.0',
  FC_REDIRECTED_TO_HINTED_IDP: '2.1.0',
  FC_REDIRECT_TO_IDP: '2.2.0',
  IDP_CHOSEN: '3.0.0',
  IDP_REQUESTED_FC_JWKS: '3.1.0',
  IDP_CALLEDBACK: '4.0.0',
  FC_REQUESTED_IDP_TOKEN: '4.1.0',
  FC_REQUESTED_IDP_USERINFO: '4.2.0',
  FC_VERIFIED: '5.0.0',
  FC_IDP_DISABLED: '5.1.0',
  FC_FQDN_MISMATCH: '6.0.0',
  FC_REDIRECTED_TO_SP: '7.0.0',
  SP_REQUESTED_FC_TOKEN: '7.1.0',
  SP_REQUESTED_FC_USERINFO: '7.2.0',
  SP_REQUESTED_LOGOUT: '8.0.0',
  FC_REQUESTED_LOGOUT_FROM_IDP: '8.1.0',
  FC_SESSION_TERMINATED: '8.2.0',
};
