// == FI
const fip = {
    // -- FIP - FIP2-HIGH - Activated
    "FIP1-HIGH": {
      uid: "fip1-high",
      name: "fip1-high",
      active: true,
      display: true,
      title: "Identity Provider - eIDAS élevé - discov - crypt",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip1-high",
      url: "https://fip1-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
      discoveryUrl:
        "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      response_types: ["code"],
      clientID: "09a1a257648c1742c74d6a3d84b31943",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip1-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP2-HIGH - Activated
    "FIP2-HIGH": {
      uid: "fip2-high",
      name: "fip2-high",
      active: true,
      display: true,
      title: "Identity Provider - eIDAS élevé - nodiscov - nocrypt",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip2-high",
      url: "https://fip2-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip2-high.docker.dev-franceconnect.fr/user/authorize",
      tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/user/token",
      userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/api/user",
      discoveryUrl: "",
      discovery: false,
      clientID: "myclientidforfip2-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip2-high.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip2-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP3-HIGH - Deactivated but visible
    "FIP3-HIGH": {
      uid: "fip-desactive-visible",
      name: "fip-desactive-visible",
      active: false,
      display: true,
      title: "FI désactivé mais visible",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "FI désactivé mais visible",
      url: "https://fip-desactive-visible.docker.dev-franceconnect.fr/",
      statusURL: "https://fip-desactive-visible.docker.dev-franceconnect.fr/",
      authzURL:
        "https://fip-desactive-visible.docker.dev-franceconnect.fr/user/authorize",
      tokenURL:
        "https://fip-desactive-visible.docker.dev-franceconnect.fr/user/token",
      userInfoURL:
        "https://fip-desactive-visible.docker.dev-franceconnect.fr/api/user",
      discoveryUrl:
        "https://fip-desactive-visible.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      clientID: "myclientidforfip-desactive-visible",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip-desactive-visible.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip-desactive-visible",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP4-HIGH - Deactivated and invisible
    "FIP4-HIGH": {
      uid: "fip4-high",
      name: "fip-desactive-invisible",
      active: false,
      display: false,
      title: "FI désactivé et invisible",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text FI 3",
      url: "https://fip2-high.docker.dev-franceconnect.fr/",
      statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip2-high.docker.dev-franceconnect.fr/user/authorize",
      tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/user/token",
      userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/api/user",
      discoveryUrl:
        "https://fip2-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      clientID: "myclientidforfip4-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip2-high.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip4-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP5-HIGH - Activated and invisible
    "FIP5-HIGH": {
      uid: "fip-active-invisible",
      name: "fip-active-invisible",
      active: true,
      display: false,
      title: "FI activé et invisible",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text FI 3",
      url: "https://fip2-high.docker.dev-franceconnect.fr/",
      statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip2-high.docker.dev-franceconnect.fr/user/authorize",
      tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/user/token",
      userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/api/user",
      discoveryUrl:
        "https://fip2-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      clientID: "myclientidforfip5-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip2-high.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip2-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP6-HIGH - whitelisted
    "FIP6-HIGH": {
      uid: "fip6-high",
      name: "fip6-high",
      active: true,
      display: true,
      title: "Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip6-high",
      url: "https://fip6-high.docker.dev-franceconnect.fr",
      authzURL: "https://fip6-high.docker.dev-franceconnect.fr/user/authorize",
      tokenURL: "https://fip6-high.docker.dev-franceconnect.fr/user/token",
      userInfoURL: "https://fip6-high.docker.dev-franceconnect.fr/api/user",
      statusURL: "https://fip6-high.docker.dev-franceconnect.fr/",
      jwksURL: "https://fip6-high.docker.dev-franceconnect.fr/certs",
      discoveryUrl: "",
      discovery: false,
      clientID: "69a1a257648c1742c74d6a3d84b31943",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip6-high.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip6-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP7-HIGH - blacklisted
    "FIP7-HIGH": {
      uid: "fip7-high",
      name: "fip7-high",
      active: true,
      display: true,
      title: "Identity Provider - eIDAS élevé - blacklisted - discov - nocrypt",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      mailto: "",
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      specificText: "specific text fip7-high",
      url: "https://fip7-high.docker.dev-franceconnect.fr/",
      statusURL: "https://fip7-high.docker.dev-franceconnect.fr/",
      discoveryUrl:
        "https://fip7-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      clientID: "79a1a257648c1742c74d6a3d84b31943",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip7-high.docker.dev-franceconnect.fr/user/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip7-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP13-HIGH - Activated - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)
    "FIP13-HIGH": {
      uid: "fip13-high",
      name: "fip13-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip13-high] - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip13-high",
      url: "https://fip13-high.docker.dev-franceconnect.fr",
      authzURL: "https://fip13-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip13-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip13-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip13-high.docker.dev-franceconnect.fr/user/session/end",
      statusURL: "https://fip13-high.docker.dev-franceconnect.fr/",
      jwksURL: "https://fip13-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip13-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "ES256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "ECDH-ES",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "ES256",
      userinfo_encrypted_response_alg: "ECDH-ES",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip13-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP14-HIGH - Activated - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)
    "FIP14-HIGH": {
      uid: "fip14-high",
      name: "fip14-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip14-high] - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "impots",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip14-high",
      url: "https://fip14-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip14-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip14-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip14-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip14-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip14-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip14-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip14-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "RS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "RS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip14-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP15-HIGH - Activated - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (ES256)
    "FIP15-HIGH": {
      uid: "fip15-high",
      name: "fip15-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip15-high] - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (ES256)",
      image: "fi-mock-substantiel.svg",
      imageFocus: "fi-mock-substantiel.svg",
      alt: "impots",
      eidas: 2,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip15-high",
      url: "https://fip15-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip15-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip15-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip15-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip15-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip15-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip15-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip15-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://fip15-high.docker.dev-franceconnect.fr/user/session/end",
      id_token_signed_response_alg: "ES256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "ECDH-ES",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "ES256",
      userinfo_encrypted_response_alg: "ECDH-ES",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip15-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP16-HIGH - Activated - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (RS256)
    "FIP16-HIGH": {
      uid: "fip16-high",
      name: "fip16-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip16-high] - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (RS256)",
      image: "fi-mock-substantiel.svg",
      imageFocus: "fi-mock-substantiel.svg",
      alt: "impots",
      eidas: 2,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip16-high",
      url: "https://fip16-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip16-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip16-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip16-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip16-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip16-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip16-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip16-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "RS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "RS256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip16-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP17-HIGH - Activated - eIDAS substantiel - crypted (none) - signed (ES256)
    "FIP17-HIGH": {
      uid: "fip17-high",
      name: "fip17-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip17-high] - eIDAS substantiel - crypted (none) - signed (ES256)",
      image: "fi-mock-substantiel.svg",
      imageFocus: "fi-mock-substantiel.svg",
      alt: "impots",
      eidas: 2,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip17-high",
      url: "https://fip17-high.docker.dev-franceconnect.fr",
      authzURL: "https://fip17-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip17-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip17-high.docker.dev-franceconnect.fr/userinfo",
      statusURL: "https://fip17-high.docker.dev-franceconnect.fr/",
      endSessionURL:
        "https://fip17-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip17-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip17-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "ES256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "ES256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip17-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP18-HIGH - Activated - eIDAS faible - crypted (none) - signed (ES256)
    "FIP18-HIGH": {
      uid: "fip18-high",
      name: "fip18-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip18-high] - eIDAS faible - crypted (none) - signed (ES256)",
      image: "fi-mock-faible.svg",
      imageFocus: "fi-mock-faible.svg",
      alt: "impots",
      eidas: 1,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip18-high",
      url: "https://fip18-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip18-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip18-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip18-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip18-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip18-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip18-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip18-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "ES256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "ES256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
  
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip18-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP19-HIGH - Activated - eIDAS faible - crypted (none) - signed (RS256)
    "FIP19-HIGH": {
      uid: "fip19-high",
      name: "fip19-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip19-high] - eIDAS faible - crypted (none) - signed (RS256)",
      image: "fi-mock-faible.svg",
      imageFocus: "fi-mock-faible.svg",
      alt: "impots",
      eidas: 1,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip19-high",
      url: "https://fip19-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip19-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip19-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip19-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip19-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip19-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip19-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip19-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "RS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "RS256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip19-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIP - FIP20-HIGH - Activated - eIDAS faible - crypted (none) - signed (HS256)
    "FIP20-HIGH": {
      uid: "fip20-high",
      name: "fip20-high",
      active: true,
      display: true,
      title:
        "Identity Provider [fip20-high] - eIDAS faible - crypted (none) - signed (HS256)",
      image: "fi-mock-faible.svg",
      imageFocus: "fi-mock-faible.svg",
      alt: "impots",
      eidas: 1,
      featureHandlers: {
        coreVerify: "core-fcp-default-verify",
        authenticationEmail: "core-fcp-send-email",
        idpIdentityCheck: "core-fcp-default-identity-check",
      },
      mailto: "",
      specificText: "specific text fip20-high",
      url: "https://fip20-high.docker.dev-franceconnect.fr",
      statusURL: "https://fip20-high.docker.dev-franceconnect.fr/",
      authzURL: "https://fip20-high.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://fip20-high.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://fip20-high.docker.dev-franceconnect.fr/userinfo",
      endSessionURL:
        "https://fip20-high.docker.dev-franceconnect.fr/user/session/end",
      jwksURL: "https://fip20-high.docker.dev-franceconnect.fr/jwks",
      discoveryUrl: "",
      discovery: false,
      response_types: ["code"],
      clientID: "myclientidforfip20-high",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      id_token_signed_response_alg: "HS256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "",
      id_token_encrypted_response_enc: "",
      userinfo_signed_response_alg: "HS256",
      userinfo_encrypted_response_alg: "",
      userinfo_encrypted_response_enc: "",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip20-high",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  
    // -- FIPEIDAS - FIPEIDASV2 - Activated
    EIDASBRIDGE: {
      uid: "eidas-bridge",
      name: "eidas-bridge",
      active: true,
      display: true,
      title: "eIDAS Identity Provider",
      image: "fi-mock-eleve.svg",
      imageFocus: "fi-mock-eleve.svg",
      alt: "eIDAS",
      eidas: 3,
      featureHandlers: {
        coreVerify: "core-fcp-eidas-verify",
        authenticationEmail: null,
        idpIdentityCheck: "core-fcp-eidas-identity-check",
      },
      mailto: "",
      specificText: "specific text eidas-bridge",
      url: "https://eidas-bridge.docker.dev-franceconnect.fr/",
      statusURL: "https://eidas-bridge.docker.dev-franceconnect.fr/",
      authzURL: "https://eidas-bridge.docker.dev-franceconnect.fr/authorize",
      tokenURL: "https://eidas-bridge.docker.dev-franceconnect.fr/token",
      userInfoURL: "https://eidas-bridge.docker.dev-franceconnect.fr/userinfo",
      discoveryUrl:
        "https://eidas-bridge.docker.dev-franceconnect.fr/.well-known/openid-configuration",
      discovery: true,
      clientID: "myclientidforeidas-bridge",
      client_secret:
        "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
      order: null,
      updatedAt: new Date("2019-04-24 17:09:17"),
      updatedBy: "admin",
      endSessionURL:
        "https://eidas-bridge.docker.dev-franceconnect.fr/session/end",
      response_types: ["code"],
      id_token_signed_response_alg: "ES256",
      token_endpoint_auth_method: "client_secret_post",
      revocation_endpoint_auth_method: "client_secret_post",
      id_token_encrypted_response_alg: "RSA-OAEP",
      id_token_encrypted_response_enc: "A256GCM",
      userinfo_signed_response_alg: "ES256",
      userinfo_encrypted_response_alg: "RSA-OAEP",
      userinfo_encrypted_response_enc: "A256GCM",
      redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/eidas-bridge",
      ],
      post_logout_redirect_uris: [
        "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
      ],
    },
  };

// -- FIs ----------

Object.values(fip).forEach((fi) => {
    print(`FIP > Initializing provider: ${fi.name} - Activated`);
    db.provider.update({ uid: fi.uid }, fi, { upsert: true });
});