server {
  listen 443 ssl;
  server_name federation-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url https://core:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name bridge-proxy-rie-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://hybridge-rie:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name admin-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://admin:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name dpa1-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://dpa1-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name dpa2-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://dpa2-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name sp1-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fsa1-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name sp2-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fsa2-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name sp3-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fsa3-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name idp1-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fia1-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name idp2-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fia2-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name idp-rie-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://fia-rie-low:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name auth.llng-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://identity-provider-llng:80;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name moncomptepro-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://moncomptepro:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name manager.llng-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://identity-provider-llng:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name reload.llng-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://identity-provider-llng:3000;
    proxy_pass $backend_url;
  }
}

server {
  listen 443 ssl;
  server_name maildev-local.proconnect.127.0.0.1.nip.io;
  include includes/common.vhost.conf;
  location / {
    set $backend_url http://maildev:1080;
    proxy_pass $backend_url;
  }
}
