version: "2.4"

####################
####################
services:
  ####################
  # Eidas MOCK
  ####################
  eidas-mock:
    hostname: eidas-mock
    image: ${FC_DOCKER_REGISTRY}/eidas-mock:2.4
    user: ${CURRENT_UID}
    volumes:
      - "${VOLUMES_DIR}/eidas/conf-eidas-mock:/data/conf-eidas:ro"
      - "${VOLUMES_DIR}/eidas/keystore-mock:/data/keystore:ro"
      - "${VOLUMES_DIR}/eidas/keystore-mock/cacerts:/etc/ssl/certs/java/cacerts:ro"
      - "${VOLUMES_DIR}/log/eidas/eidas-mock:/data/log/tomcat"
      - "${VOLUMES_DIR}/log/eidas/eidas-mock:/data/log/eidas"
    environment:
      - "VIRTUAL_HOST=eidas-mock.docker.dev-franceconnect.fr"
      - "VIRTUAL_PORT=443"
      - "App_PROTOCOL=https"
      - "TZ=Europe/Paris"
      - "JAVA_OPTS=-Xms512m  -Xmx512m"
      - "LOG_LEVEL=INFO"
    networks:
      - eidas
      - public
