version: '3.4'

####################
####################
services:
  ####################
  # Eidas FR
  ####################
  eidas-fr:
    hostname: eidas-fr
    build:
      context: '${WORKING_DIR}'
      dockerfile: '${WORKING_DIR}/builds/eidas/Dockerfile'
      args:
        FC_DOCKER_REGISTRY: ${FC_DOCKER_REGISTRY}
    ports:
      - '10900:10900'
    volumes:
      - '${VOLUMES_DIR}/eidas/conf-eidas-fr:/data/conf-eidas:ro'
      - '${VOLUMES_DIR}/eidas/keystore-fr:/data/keystore:ro'
      - '${VOLUMES_DIR}/log/eidas/eidas-fr:/data/log/tomcat'
      - '${VOLUMES_DIR}/log/eidas/eidas-fr:/data/log/eidas'
    environment:
      - 'VIRTUAL_HOST=eidas-fr.docker.dev-franceconnect.fr'
      - 'VIRTUAL_PORT=8080'
      - 'TZ=Europe/Paris'
      - 'JAVA_OPTS=-Xms1G -Xmx1G'
      - 'LOG_LEVEL=INFO'
    networks:
      - eidas
      - public
    command: 'tail -f /dev/null'
