include: '/back/.gitlab-build-template.yml'

partners-fcp/back-build-image:
  extends: .base-build
  variables:
    APP: partners-fcp
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\npartners_back_version:"

partners-fcp/back-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: partners-fcp
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\npartners_back_version:"
  needs:
    - job: partners-fcp/back-build-image
