include: '/front/.gitlab-build-template.yml'

fca/build-front:
  extends: .base-build-front
  variables:
    APP: agent-connect
    MSG: "environments/nubo01-fca-integ/group_vars/all/versions.yml\nenvironments/nubo12-fca-integ/group_vars/all/versions.yml\nfca_front_version:"

fca/tag-front-to-prod:
  extends: .base-tag-front-to-prod
  variables:
    APP: agent-connect
    MSG: "environments/nubo01-fca-prod/group_vars/all/versions.yml\nenvironments/nubo12-fca-prod/group_vars/all/versions.yml\nfca_front_version:"
  needs:
    - job: fca/build-front
