export enum OidcProviderRoutes {
  AUTHORIZATION = '/authorize',
  AUTHORIZATION_RESUME = '/authorize/:id',
  REDIRECT_TO_SP = '/login',
  CHECK_SESSION = '/session/check',
  CODE_VERIFICATION = '/device',
  DEVICE_AUTHORIZATION = '/device/auth',
  END_SESSION = '/session/end',
  END_SESSION_CONFIRM = '/session/end/confirm',
  END_SESSION_SUCCESS = '/session/end/success',
  JWKS = '/jwks',
  PUSHED_AUTHORIZATION_REQUEST = '/request',
  REGISTRATION = '/reg',
  TOKEN = '/token',
  INTROSPECTION = '/token/introspection',
  REVOCATION = '/token/revocation',
  USERINFO = '/userinfo',
  OPENID_CONFIGURATION = '/.well-known/openid-configuration',
}
