export enum ErrorCode {
  DISABLED_PROVIDER = 17,
  MISSING_PROVIDER = 19,
  TOKEN_FAILED = 26,
  USERINFO_FAILED = 27,
  TOKEN_VALIDATION_FAILED = 30,
  ISSUER_DISCOVERY_FAILED = 31,
  AUTHORIZATION_RESPONSE_ERROR = 32,
}
