export enum ErrorCode {
  DISABLED_PROVIDER = 17,
  MISSING_PROVIDER = 19,
  MISSING_STATE = 21,
  INVALID_STATE = 22,
  TOKEN_FAILED = 26,
  USERINFO_FAILED = 27,
  GET_END_SESSION_URL = 28,
  TOKEN_RESULT_FAILED = 30,
  ISSUER_DISCOVERY_FAILED = 31,
}
