services:
  core-fca-low:
    hostname: core-fca-low
    build:
      context: '../../../back'
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '../../../back/apps:/var/www/app/apps:ro'
      - '../../../back/instances:/var/www/app/instances:ro'
      - '../../../back/libs:/var/www/app/libs:ro'
      - '../../volumes/app:/opt/scripts'
      - '../../volumes/log:/var/log/app'
      - '../../volumes/.home:/home'
      - '../../volumes/ssl:/etc/ssl/docker_host:ro'
    tmpfs:
      - /var/www/app/dist:mode=777
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-fca-low.env'
    tty: true
    networks:
      - fc
      - public
      - data
    init: true

  core-fca-low-squid:
    extends: core-fca-low
    hostname: core-fca-low-squid
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
      squid:
        condition: service_healthy
    environment:
      # Proxy Configuration for Hybridge
      GLOBAL_AGENT_HTTP_PROXY: http://squid:3128
      GLOBAL_AGENT_HTTPS_PROXY: http://squid:3128
