services:
  core:
    hostname: core
    extends:
      file: ../shared/shared.yml
      service: base-core
    ports:
      - 9229:9229
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'

  core-squid:
    extends: core
    hostname: core-fca-low-squid
    depends_on:
      squid:
        condition: service_started
    environment:
      # Proxy Configuration for Hybridge
      GLOBAL_AGENT_HTTP_PROXY: http://squid:3128
      GLOBAL_AGENT_HTTPS_PROXY: http://squid:3128

  core-rie:
    extends: core
    hostname: core-rie
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-rie.env'
