services:
  core-fca-rie:
    hostname: core-fca-rie
    build:
      context: '../../../back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '../../../back:/var/www/app'
      - '/var/www/app/node_modules'
      - '../../volumes/app:/opt/scripts'
      - '../../volumes/log:/var/log/app'
      - '../../volumes/.home:/home'
      - '../../volumes/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-fca-rie.env'
    tty: true
    networks:
      - fc
      - data
      - public
    init: true
