####################
####################
services:
  core-fca-low:
    hostname: core-fca-low
    # build:
    #   context: '${FEDERATION_DIR}/back'
    #   target: dev
    #   args:
    #     INSTANCE: core-fca-low
    image: pc-nodejs
    build:
      {
        context: '${COMPOSE_DIR}/../builds/node',
        args: { NODE_VERSION: '${NODE_VERSION}' },
      }
    #command: '/opt/scripts/start.sh'
    #command: yarn start:dev core-fca-low
    # develop:
    #   watch:
    #     - action: sync
    #       path: '${FEDERATION_DIR}/back'
    #       target: /var/www/app
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: /var/www/app/yarn.lock
    working_dir: /var/www/app
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'
    tty: true
    networks:
      - fc
      - public
      - data
    init: true
