####################
####################
services:
  core-prod:
    hostname: core-prod
    image: ghcr.io/proconnect-gouv/federation/core-fca-low:test-build-docker-2
    working_dir: /var/www/app
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-prod.env'
    tty: true
    networks:
      - fc
      - public
      - data
    init: true
    command: 'pm2 logs'
