services:
  core:
    hostname: core
    extends:
      file: ../shared/shared.yml
      service: base-core
    ports:
      - 9229:9229
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-fca-low.env'

  core-squid:
    extends: core
    hostname: core-fca-low-squid
    depends_on:
      squid:
        condition: service_started
    environment:
      # Proxy Configuration for Hybridge
      GLOBAL_AGENT_HTTP_PROXY: http://squid:3128
      GLOBAL_AGENT_HTTPS_PROXY: http://squid:3128

  core-rie:
    extends: core
    hostname: core-rie
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-fca-rie.env'

  core-prod:
    hostname: core-prod
    image: ghcr.io/proconnect-gouv/federation/core-fca-low:${GITHUB_PACKAGE_VERSION:-latest}
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-fca-prod.env'
    depends_on:
      rp-all:
        condition: service_started
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    tty: true
    networks:
      - fc
      - public
      - data
    init: true
    volumes:
      - '../../volumes/app:/opt/scripts'
      - '../../volumes/log:/var/log/app'
      - '../../volumes/.home:/home'
      - '../../volumes/ssl:/etc/ssl/docker_host:ro'
    command: pm2-runtime /etc/pm2/app.json
