services:
  core:
    hostname: core
    extends:
      file: ../shared/shared.yml
      service: base-core
    ports:
      - 9229:9229
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core.env'
    depends_on:
      squid:
        condition: service_started

  core-rie:
    extends: core
    hostname: core-rie
    env_file:
      - '../shared/.env/base-app.env'
      - '../fca-low/.env/core-rie.env'
