####################
####################
services:
  core-fca-rie:
    hostname: core-fca-rie
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
      args:
        INSTANCE: core-fca-low
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-rie.env'
    tty: true
    networks:
      - fc
      - data
      - public
    init: true
    command: 'pm2 logs'
