####################
####################
services:
  core-fca-low:
    hostname: core-fca-low
    image: pc-nodejs
    build:
      {
        context: '${COMPOSE_DIR}/../builds/node',
        args: { NODE_VERSION: '${NODE_VERSION}' },
      }
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      init-core-fca-low:
        condition: service_completed_successfully
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'
    tty: true
    networks:
      - fc
      - public
      - data
    init: true
    command: 'pm2 logs'

  init-core-fca-low:
    build:
      args:
        INSTANCE: core-fca-low
      context: '${FEDERATION_DIR}/back'
    working_dir: /build/back
    depends_on:
      mongo-fca-low:
        condition: service_healthy
    volumes:
      - '${VOLUMES_DIR}/src/fc/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'
    environment:
      - NODE_OPTIONS="--experimental-strip-types"
    networks:
      - data
    command: 'npm run migrate up'
