####################
####################
services:
  core-fca-low:
    hostname: core-fca-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
      args:
        INSTANCE: core-fca-low
    working_dir: /var/www/app
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
      node-modules-installer:
        condition: service_completed_successfully
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - 'node-modules:/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'
    tty: true
    networks:
      - fc
      - public
      - data
    init: true
<<<<<<< HEAD
    command: 'pm2 logs'

  core-fca-low-squid:
    extends: core-fca-low
    hostname: core-fca-low-squid
    depends_on:
      mongo-fca-low:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
      squid:
        condition: service_started
    environment:
      # Proxy Configuration for Hybridge
      GLOBAL_AGENT_HTTP_PROXY: http://squid:3128
      GLOBAL_AGENT_HTTPS_PROXY: http://squid:3128
    command: 'node dist/instances/core-fca-low/main.js'
=======
    command: 'yarn start:dev core-fca-low'
>>>>>>> a717120122 ([PCF-710]🔨 Start core in dev mode)
