services:
  core-fca-low:
    hostname: core-fca-low
    extends:
      file: ../shared/shared.yml
      service: base-core
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-low.env'

  core-fca-low-squid:
    extends: core-fca-low
    hostname: core-fca-low-squid
    depends_on:
      squid:
        condition: service_started
    environment:
      # Proxy Configuration for Hybridge
      GLOBAL_AGENT_HTTP_PROXY: http://squid:3128
      GLOBAL_AGENT_HTTPS_PROXY: http://squid:3128

  core-fca-rie:
    extends: core-fca-low
    hostname: core-fca-rie
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/core-fca-rie.env'
