version: "3.4"

####################
####################
services:
  exploit-fca-low-front:
    hostname: exploit-fca-low-front
    image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "squid"
      - "exploit-fca-low"
    volumes:
      - "${VOLUMES_DIR}/src/fc/front/apps/exploit-fca-low:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
    environment:
      - "EVT_LOG_FILE=/var/log/app/exploit-fca-low-front.log"
      - "FQDN=exploit-fca-low.docker.dev-franceconnect.fr"
      - "PM2_CWD=/var/www/app"
      - "PM2_SCRIPT=yarn start"
      - "VIRTUAL_HOST=exploit-fca-low.docker.dev-franceconnect.fr"
      - "VIRTUAL_HOST_PATH=/"
    networks:
      - exploitation
      - data
    command: "tail -f /dev/null"
