####################
####################
services:
  ####################
  # FC-EXPLOITATION
  ####################
  exploitation-fca-low:
    hostname: exploitation-fca-low
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app/fc-exploitation
    depends_on:
      pg-exploitation-fca-low:
        condition: service_started
      mongo-fca-low:
        condition: service_healthy
      squid:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${VOLUMES_DIR}/src/proconnect-exploitation:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
      - '${VOLUMES_DIR}/log:/var/log/app'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/shared/.env/postgres.env'
      - '${COMPOSE_DIR}/shared/.env/fc-mongo.env'
      - '${COMPOSE_DIR}/fca-low/.env/exploitation-fca-low.env'
    networks:
      - data
    init: true
    command: 'tail -f /dev/null'
