services:
  ####################
  ##
  ##   RIE network
  ##
  ####################
  hybridge-rie:
    hostname: hybridge-rie
    build:
      context: "../../.."
      dockerfile: "csmr-rie/Dockerfile"
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      - broker
    volumes:
      - "../../../csmr-rie/src:/var/www/app/csmr-rie/src:ro"
      - "../../../back/libs:/var/www/app/back/libs:ro"
      - "../../volumes/app:/opt/scripts"
      - "../../volumes/log/:/var/log/app"
      - "../../volumes/.home:/home"
      - ../../volumes/ssl:/etc/ssl/docker_host:ro
    tmpfs:
      - /var/www/app/csmr-rie/dist:mode=777
    env_file:
      - "../shared/.env/base-app.env"
      - "../fca-low/.env/hybridge-rie.env"
    tty: true
    networks:
      - rie
    init: true
    command: "yarn start:dev"
