services:
  ####################
  ##
  ##   PUBLIC network
  ##
  ####################

  rp-hybridge:
    image: nginx:1.14.2
    volumes:
      - ${VOLUMES_DIR}/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${VOLUMES_DIR}/nginx-proxy/includes:/etc/nginx/includes:ro
      - ${VOLUMES_DIR}/rp-bridge-proxy/:/etc/nginx/conf.d:ro
      - ${VOLUMES_DIR}/ssl:/etc/nginx/docker_host:ro
    networks:
      public:
        ipv4_address: 172.16.1.254
    depends_on:
      - hybridge-internet

  hybridge-internet:
    hostname: hybridge-internet
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      rp-all:
        condition: service_started
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/bridge-proxy-rie.env'
    tty: true
    networks:
      - public
      - data
    init: true

  ####################
  ##
  ##   RIE network
  ##
  ####################
  hybridge-rie:
    hostname: hybridge-rie
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - broker
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - ${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/csmr-rie.env'
    tty: true
    networks:
      - rie
    init: true
    command: 'yarn start:dev csmr-rie'
