services:
  ####################
  ##
  ##   PUBLIC network
  ##
  ####################

  rp-bridge-proxy:
    image: nginx:1.14.2
    volumes:
      - ${VOLUMES_DIR}/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${VOLUMES_DIR}/nginx-proxy/includes:/etc/nginx/includes:ro
      - ${VOLUMES_DIR}/rp-bridge-proxy/:/etc/nginx/conf.d:ro
      - ${VOLUMES_DIR}/ssl:/etc/nginx/docker_host:ro
    networks:
      public:
        ipv4_address: 172.16.1.254
    depends_on:
      - bridge-proxy-rie

  bridge-proxy-rie:
    extends:
      file: ../shared/shared.yml
      service: base-nodejs-app
    hostname: bridge-proxy-rie
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/fca-low/.env/bridge-proxy-rie.env'
    networks:
      - public
      - data

  ####################
  ##
  ##   RIE network
  ##
  ####################
  csmr-rie:
    extends:
      file: ../shared/shared.yml
      service: base-rie
    hostname: csmr-rie
    depends_on:
      - broker
    env_file:
      - '${COMPOSE_DIR}/fca-low/.env/csmr-rie.env'

  fia-llng-low:
    build:
      context: '${WORKING_DIR}'
      dockerfile: '${WORKING_DIR}/builds/lemonldap/Dockerfile'
    volumes:
      - '${VOLUMES_DIR}/llng/scripts/:/scripts:ro'
      - '${VOLUMES_DIR}/llng/llng-conf.json:/llng-conf.json:ro'
    env_file:
      - '${COMPOSE_DIR}/fca-low/.env/fia-llng-low.env'
    networks:
      - rie

  fia-rie-low:
    extends:
      file: ../shared/shared.yml
      service: base-rie
    hostname: fia-rie-low
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/fca-low/mocks/idp/databases:/var/databases'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/fca-low/.env/fia-rie-low.env'
