services:
  ####################
  # SP Mocks
  ####################

  fsa1-low:
    hostname: fsa1-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fsa1-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  fsa2-low:
    hostname: fsa2-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fsa2-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  fsa3-low:
    hostname: fsa3-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fsa3-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  fsa4-low:
    hostname: fsa4-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fsa4-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  ####################
  # IDP Mocks
  ####################

  fia1-low:
    hostname: fia1-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/fca-low/mocks/idp/databases:/var/databases'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fia1-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  fia2-low:
    hostname: fia2-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/fca-low/mocks/idp/databases:/var/databases'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/fia2-low.env'
    tty: true
    networks:
      - public
      - data
    init: true

  moncomptepro:
    hostname: moncomptepro
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      redis-pwd:
        condition: service_healthy
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/fca-low/mocks/idp/databases:/var/databases'
      - '${VOLUMES_DIR}/log/:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/moncomptepro.env'
    tty: true
    networks:
      - public
      - data
    init: true

  ####################
  # DP Mocks
  ####################

  dpa1-low:
    hostname: dpa1-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/dpa1-low.env'
    networks:
      - public
    init: true

  dpa2-low:
    hostname: dpa2-low
    build:
      context: '${FEDERATION_DIR}/back'
      target: dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    volumes:
      - '${FEDERATION_DIR}/back:/var/www/app'
      - '/var/www/app/node_modules'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/dpa2-low.env'
    networks:
      - public
    init: true
