version: "3.4"

####################
####################
services:
  ####################
  ##
  ##   RIE-BRIDGE-PROXY
  ##
  ####################

  rie-bridge-proxy:
    hostname: rie-bridge-proxy
    image: gitlab.dev-franceconnect.fr:5005/france-connect/fc-docker/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - 'squid'
    volumes:
      - '${VOLUMES_DIR}/src/fc/back:/var/www/app'
      - '${VOLUMES_DIR}/app:/opt/scripts'
      - '${VOLUMES_DIR}/log:/var/log/app'
      - '${VOLUMES_DIR}/.home:/home'
      - '${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro'
    env_file:
      - '${COMPOSE_DIR}/shared/.env/base-app.env'
      - '${COMPOSE_DIR}/fca-low/.env/rie-bridge-proxy.env'
    tty: true
    ports:
      - 9262:9262
    networks:
      - public
      - data
    command: 'pm2 logs'
