version: "3.4"

####################
####################
services:
  min-fca-low:
    image: alpine
    depends_on:
      - "fca"
      - "fca-front"
      - "fsa1-low"
      - "fia1-low"
      
  all-fca-low:
    image: alpine
    depends_on:
      - "fca"
      - "fca-front"
      - "fsa1-low"
      - "fsa2-low"
      - "fsa3-low"
      - "fsa4-low"
      - "fia1-low"
      - "fia2-low"
      - "fia4-low"
      - "fia5-low"
      - "exploitation-fca"
      - "pg-exploitation-fca"
      - "exploit-fca"
      - "exploit-fca-front"
