include:
  - ../shared/shared.yml
  - postgres.yml
  - mongo.yml
  - core.yml
  - mocks.yml
  - admin.yml
  - hybridge.yml

services:
  small:
    image: alpine
    depends_on:
      - 'core'
      - 'service-provider-1'
      - 'identity-provider-1'

  # -- used for e2e tests
  medium:
    image: alpine
    depends_on:
      - 'core'
      - 'admin'
      # -- SP
      - 'service-provider-1'
      - 'service-provider-2'
      - 'service-provider-4'
      # -- IdP
      - 'identity-provider-1'
      - 'identity-provider-2'
      - 'proconnect-identite'
      # -- DP
      - 'resource-server-1'
      - 'resource-server-2'

  large:
    image: alpine
    depends_on:
      - 'core'
      - 'service-provider-1'
      - 'service-provider-2'
      - 'service-provider-3'
      - 'service-provider-4'
      - 'identity-provider-1'
      - 'identity-provider-2'
      - 'proconnect-identite'
      - 'admin'
      ### Hybridge
      - 'lemon-ldap'
      - 'rp-hybridge'
      - 'hybridge-internet'
      - 'hybridge-rie'

  lemon-ldap:
    image: alpine
    depends_on:
      - 'identity-provider-llng'
      - 'openldap'

  hybridge:
    image: alpine
    depends_on:
      - 'core-squid'
      - 'service-provider-1'
      - 'identity-provider-1'
      ### RIE
      - 'squid'
      - 'hybridge-internet'
      - 'hybridge-rie'
      - 'identity-provider-rie'
      - 'rp-hybridge'

  prod:
    image: alpine
    depends_on:
      - 'core-prod'
      - 'service-provider-1'
      - 'identity-provider-1'
      - 'admin'
