version: '3.4'

####################
####################
services:
  min-fca-low:
    image: alpine
    depends_on:
      - 'core-fca-low'
      - 'fca-low-front'
      - 'fsa1-low'
      - 'fia1-low'

  exploit-fca-low:
    image: alpine
    depends_on:
      - 'exploit-fca-low-back'
      - 'exploit-fca-low-front'

  all-fca-low:
    image: alpine
    depends_on:
      - 'core-fca-low'
      - 'fca-low-front'
      - 'fsa1-low'
      - 'fsa2-low'
      - 'fsa3-low'
      - 'fsa4-low'
      - 'fia1-low'
      - 'fia2-low'
      - 'fia4-low'
      - 'fia5-low'
      - 'exploitation-fca-low'
      - 'pg-exploit-fca-low'
      - 'exploit-fca-low-back'
      - 'exploit-fca-low-front'
      ### RIE
      - 'rp-bridge-proxy'
      - 'rie-bridge-proxy'
      - 'csmr-rie'

  hybridge-fca-low:
    image: alpine
    depends_on:
      - 'min-fca-low'
      - 'fia-llng-low'
      - 'openldap'
      ### RIE
      - 'rp-bridge-proxy'
      - 'rie-bridge-proxy'
      - 'csmr-rie'
