include:
  - ../shared/shared.yml
  - postgres.yml
  - mongo.yml
  - core.yml
  - mocks.yml
  - exploitation-fca-low.yml
  - hybridge.yml

services:
  small:
    image: alpine
    depends_on:
      - 'core-fca-low'
      - 'fsa1-low'
      - 'fia1-low'

  # -- used for e2e tests
  medium:
    image: alpine
    depends_on:
      - 'core-fca-low'
      - 'exploitation-fca-low'
      # -- SP
      - 'fsa1-low'
      - 'fsa2-low'
      - 'fsa4-low'
      # -- IdP
      - 'fia1-low'
      - 'fia2-low'
      - 'moncomptepro'
      # -- DP
      - 'dpa1-low'
      - 'dpa2-low'

  large:
    image: alpine
    depends_on:
      - 'core-fca-low'
      - 'fsa1-low'
      - 'fsa2-low'
      - 'fsa3-low'
      - 'fsa4-low'
      - 'fia1-low'
      - 'fia2-low'
      - 'moncomptepro'
      - 'exploitation-fca-low'
      ### Hybridge
      - 'lemon-ldap'
      - 'rp-bridge-proxy'
      - 'bridge-proxy-rie'
      - 'csmr-rie'

  lemon-ldap:
    image: alpine
    depends_on:
      - 'fia-llng-low'
      - 'openldap'

  hybridge:
    image: alpine
    depends_on:
      - 'core-fca-low-squid'
      - 'fsa1-low'
      - 'fia1-low'
      ### RIE
      - 'squid'
      - 'bridge-proxy-rie'
      - 'csmr-rie'
      - 'fia-rie-low'
      - 'rp-bridge-proxy'
