include:
  - ../shared/shared.yml
  - postgres.yml
  - mongo.yml
  - core.yml
  - mocks.yml
  - admin.yml
  - hybridge.yml

services:
  small:
    image: alpine
    depends_on:
      - 'core'
      - 'fsa1-low'
      - 'fia1-low'

  # -- used for e2e tests
  medium:
    image: alpine
    depends_on:
      - 'core'
      - 'admin'
      # -- SP
      - 'fsa1-low'
      - 'fsa2-low'
      - 'fsa4-low'
      # -- IdP
      - 'fia1-low'
      - 'fia2-low'
      - 'moncomptepro'
      # -- DP
      - 'dpa1-low'
      - 'dpa2-low'

  lemon-ldap:
    image: alpine
    depends_on:
      - 'identity-provider-llng'
      - 'openldap'

  hybridge:
    image: alpine
    depends_on:
      - 'core'
      - 'fsa1-low'
      - 'fia1-low'
      ### RIE
      - 'squid'
      - 'hybridge-internet'
      - 'hybridge-rie'
      - 'fia-rie-low'
      - 'rp-hybridge'

  rie:
    image: alpine
    depends_on:
      - 'core-rie'
      - 'fsa1-low'
      - 'fia1-low'
