include:
  - ../shared/shared.yml
  - postgres.yml
  - mongo.yml
  - core.yml
  - mocks.yml
  - exploitation-fca-low.yml
  - hybridge.yml
  - core-rie.yml

services:
  small:
    image: alpine
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      rp-all:
        condition: service_started
      core-fca-low:
        condition: service_started
      fsa1-low:
        condition: service_started
      fia1-low:
        condition: service_started

  # -- used for e2e tests
  medium:
    image: alpine
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      rp-all:
        condition: service_started
      core-fca-low:
        condition: service_started
      exploitation-fca-low:
        condition: service_healthy
      # -- SP
      fsa1-low:
        condition: service_started
      fsa2-low:
        condition: service_started
      fsa4-low:
        condition: service_started
      # -- IdP
      fia1-low:
        condition: service_started
      fia2-low:
        condition: service_started
      moncomptepro:
        condition: service_started
      # -- DP
      dpa1-low:
        condition: service_started
      dpa2-low:
        condition: service_started

  large:
    image: alpine
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      rp-all:
        condition: service_started
      core-fca-low:
        condition: service_started
      fsa1-low:
        condition: service_started
      fsa2-low:
        condition: service_started
      fsa3-low:
        condition: service_started
      fsa4-low:
        condition: service_started
      fia1-low:
        condition: service_started
      fia2-low:
        condition: service_started
      moncomptepro:
        condition: service_started
      exploitation-fca-low:
        condition: service_healthy
      ### Hybridge
      lemon-ldap:
        condition: service_started
      rp-bridge-proxy:
        condition: service_started
      bridge-proxy-rie:
        condition: service_started
      csmr-rie:
        condition: service_started

  lemon-ldap:
    image: alpine
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      fia-llng-low:
        condition: service_started
      openldap:
        condition: service_started

  hybridge:
    image: alpine
    command: ["sleep", "infinity"]
    init: true
    depends_on:
      rp-all:
        condition: service_started
      core-fca-low-squid:
        condition: service_started
      fsa1-low:
        condition: service_started
      fia1-low:
        condition: service_started
      ### RIE
      squid:
        condition: service_healthy
      bridge-proxy-rie:
        condition: service_started
      csmr-rie:
        condition: service_started
      fia-rie-low:
        condition: service_started
      rp-bridge-proxy:
        condition: service_started
