####################
####################
services:
  min-fca-low:
    image: alpine
    depends_on:
      - "core-fca-low"
      - "fsa1-low"
      - "fia1-low"

  min-fca-rie:
    image: alpine
    depends_on:
      - "core-fca-rie"
      - "fsa1-low"
      - "fia1-low"

  bdd-fca-low:
    image: alpine
    depends_on:
      - "core-fca-low"
      - "exploitation-fca-low"
      # -- SP
      - "fsa1-low"
      - "fsa2-low"
      - "fsa4-low"
      - "fsa5-low"
      # -- IdP
      - "fia1-low"
      - "fia2-low"
      - "fia4-low"
      - "fia5-low"
      - "fia8-low"
      - "moncomptepro"
      # -- DP
      - "dpa1-low"
      - "dpa2-low"

  all-fca-low:
    image: alpine
    depends_on:
      - "core-fca-low"
      - "fsa1-low"
      - "fsa2-low"
      - "fsa3-low"
      - "fsa4-low"
      - "fsa5-low"
      - "fia1-low"
      - "fia2-low"
      - "fia4-low"
      - "fia5-low"
      - "fia8-low"
      - "moncomptepro"
      - "exploitation-fca-low"
      ### Hybridge
      - "lemon-ldap"
      - "rp-bridge-proxy"
      - "bridge-proxy-rie"
      - "csmr-rie"

  lemon-ldap:
    image: alpine
    depends_on:
      - "fia-llng-low"
      - "openldap"

  hybridge-fca-low:
    image: alpine
    depends_on:
      - "min-fca-low"
      - "rp-bridge-proxy"
      - "bridge-proxy-rie"
      ### RIE
      - "lemon-ldap"
      - "csmr-rie"
      - "fia-rie-low"

  dp-fca-low:
    image: alpine
    depends_on:
      - "core-fca-low"
      # -- SP
      - "fsa1-low"
      # -- IdP
      - "fia1-low"
      # -- DP
      - "dpa1-low"
      - "dpa2-low"
