version: "3"

services:
  POSTGRES:
    image: postgres:11.2-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: "typeormtest"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "testdb"
    ports:
      - "5432:5432"
    restart: always