quality-fca-low-release:
  stage: 'Post-deploy'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - docker
  only:
    - tags
  when: manual
  environment:
    name: integ01
    url: https://fca.integ01.dev-agentconnect.fr
  variables:
    FC_ROOT: '$CI_BUILDS_DIR/france-connect'
    CYPRESS_PLATFORM: 'fca-low'
    CYPRESS_TEST_ENV: 'integ01'
  before_script:
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  # Build the nginx proxy to access /integ01/fca.html
    - docker-stack up rp-all
    - cd quality/fca
    - yarn install
    - export CYPRESS_EXPLOIT_USER_PASS=$EXPLOIT_FCA_LOW_INT_PWD
    - export CYPRESS_EXPLOIT_USER_TOTP=$EXPLOIT_FCA_LOW_INT_TOTP
    - yarn test:low:chrome-desktop -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - yarn report:generate
    - exit $RETURN_CODE
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - $CI_PROJECT_DIR/quality/fca/cypress/reports/cucumber/html-report  
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
