quality-fca-low-release:
  stage: 'Post-deploy'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - cypress
  only:
    - tags
  when: manual
  environment:
    name: integ01
    url: https://fca.integ01.dev-agentconnect.fr
  variables:
    CYPRESS_PLATFORM: 'fca-low'
    CYPRESS_TEST_ENV: 'integ01'
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      - quality/node_modules/
  before_script:
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd $CI_PROJECT_DIR/quality/fca && yarn install
    - cd $CI_PROJECT_DIR
  script:
  # Build the nginx proxy to access /integ01/fca.html
    - docker-stack up rp-all
    - cd $CI_PROJECT_DIR/quality/fca
    - export CYPRESS_EXPLOIT_USER_PASS=$EXPLOIT_FCA_LOW_INT_PWD
    - export CYPRESS_EXPLOIT_USER_TOTP=$EXPLOIT_FCA_LOW_INT_TOTP
    - yarn test:low:ci -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - yarn report:generate
    - exit $RETURN_CODE
  dependencies: []
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - quality/fca/cypress/reports/cucumber/html-report
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
