core-fca-low:
  stage: 'End to end'
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  tags:
    - docker
  variables:
    FC_ROOT: '$CI_BUILDS_DIR/france-connect'
    TZ: 'Europe/Paris'
  cache:
    key: '${CI_PROJECT_ID}'
    policy: pull
    paths:
      - back/node_modules/
      - front/apps/agent-connect/node_modules/
  before_script:
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc
    - ln -s $FC_ROOT/fc/front/apps/user-dashboard $FC_ROOT/fc/docker/volumes/src/user-dashboard
    - ln -s $FC_ROOT/fc/front/apps/agent-connect $FC_ROOT/fc/docker/volumes/src/agent-connect
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do ln -s $mock $FC_ROOT/fc/docker/volumes/src; done
  script:
    - docker-stack up all-fca-low
    - docker-stack fca-low-front &
    - docker-stack dep core-fca-low
    - docker-stack start fsa1-low fsa2-low fsa4-low fia1-low fia2-low fia4-low fia5-low
    - wait
    - docker-stack start core-fca-low fca-low-front
    # ## -- Build like for prod
    #- docker-stack exec fsa1-low yarn build mock-service-provider-fcp-high # Will build for fsa2-low as well
    #- docker-stack exec fca yarn build core-fca-low
    #- docker-stack exec csmr-hsm yarn build csmr-hsm-high
    # ## -- Launch like prod
    #- docker-stack exec fsa1-low yarn start:prod:mock-service-provider-fcp-high &
    #- docker-stack exec fsa2-low yarn start:prod:mock-service-provider-fcp-high &
    #- docker-stack exec fca yarn start:prod:core-fca-low &
    #- docker-stack exec csmr-hsm yarn start:prod:csmr-hsm-high &
    # Starting Cypress
    - timeout 120 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://core-fca-low.docker.dev-franceconnect.fr/api/v2/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for core-fca-low..." && sleep 10; done' || (
      (echo 'Cannot connect to core-fca-low') &&
      (docker exec fc_core-fca-low_1 cat /tmp/.pm2/logs/core-fca-low-error-0.log || true) &&
      (docker exec fc_core-fca-low_1 cat /tmp/.pm2/logs/core-fca-low-out-0.log || true) &&
      exit 1)
    - npx cypress${CYPRESS_VERSION} run -c video=${CYPRESS_VIDEO} -P back/instances/core-fca-low || (
      (docker cp fc_core-fca-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fia1-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fia2-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fia4-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fia5-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fsa1-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fsa2-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fsa4-low_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc_fca-low-front_1:/tmp/.pm2/logs back/instances/core-fca-low/cypress || true) &&
      (docker cp fc-rp-all:/var/log/nginx back/instances/core-fca-low/cypress/logs || true) &&
      exit 1)
  interruptible: true
  artifacts:
    expire_in: 1 hrs
    when: on_failure
    paths:
      - back/instances/core-fca-low/cypress/screenshots
      - back/instances/core-fca-low/cypress/videos
      - back/instances/core-fca-low/cypress/logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
