review-fca-low:
  stage: 'Review'
  image: ${DEPLOY_IMAGE}
  tags:
    - recette
  only:
    - fca-staging
  variables:
    GIT_STRATEGY: none
    PC_APPS_VERSION: 'fca-staging'
  script:
    - chmod og= $RECETTE_SSH_KEY
    - ssh -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER "sh /data/fca/start $CI_COMMIT_REF_NAME $PC_APPS_VERSION $CI_JOB_TOKEN $CI_REGISTRY $CI_OPEN_MERGE_REQUESTS"
  resource_group: recette
  dependencies: []
  environment:
    name: recette
    on_stop: stop-fca-low
    auto_stop_in: 1 hour
  when: manual

stop-fca-low:
  stage: 'Review'
  image: ${DEPLOY_IMAGE}
  tags:
    - recette
  variables:
    GIT_STRATEGY: none
  script:
    - chmod og= $RECETTE_SSH_KEY
    - ssh -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER "sh /data/teardown fca"
    - scp -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER:/data/fca/workspace/fc/docker/volumes/log/*.log .
  artifacts:
    expire_in: 1 hrs
    paths:
      - ./
  resource_group: recette
  dependencies: []
  environment:
    name: recette
    action: stop
  only:
    - fca-staging
  when: manual
