fca-low:
  stage: 'End to end'
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  timeout: 1h
  tags:
    - cypress
  variables:
    TZ: 'Europe/Paris'
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      # Back
      - back/node_modules/
      # Front
      - front/node_modules/
      - front/apps/agent-connect/node_modules/
      - front/apps/exploit-fca-low/node_modules/
      - front/apps/exploit-fcp-high/node_modules/
      - front/apps/partners-fca/node_modules/
      - front/apps/partners-fcp/node_modules/
      - front/apps/user-dashboard/node_modules/
      # Quality
      - quality/node_modules/
      # Fc-apps
      - cache/fc-apps/fc-exploitation/node_modules/
      - cache/fc-apps/fc-stats/node_modules/
      - cache/fc-apps/fc-support/node_modules/
      - cache/fc-apps/fc-workers/node_modules/
      - cache/fc-apps/node_modules/
      - cache/fc-apps/shared/node_modules/
      # Cypress
      - cache/Cypress
  before_script:
    # Ensure a clean docker environnement
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - RETURN_CODE=0
    # Shallow clone depth 1 FC-APP repository
    - rm -rf $FC_ROOT/fc-apps
    - git clone -b $FC_APPS_VERSION --depth 1 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-apps.git $FC_ROOT/fc-apps
    # Bind sources in docker volumes
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc
    - ln -s $FC_ROOT/fc/front/apps/agent-connect $FC_ROOT/fc/docker/volumes/src/agent-connect
    - ln -s $FC_ROOT/fc-apps $FC_ROOT/fc/docker/volumes/src/fc-apps
    # Return to project directory
    - wait
    - cd $CI_PROJECT_DIR
  script:
    # Up the docker-stack with minimal requirement
    - docker-stack up bdd-fca-low
    - docker exec fc_core-fca-low_1 bash -c "yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION"
    - docker exec fc_fca-low-front_1 bash -c "yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION"
    - docker-stack fca-low-front
    - docker-stack dep core-fca-low
    - rsync -a $CI_PROJECT_DIR/cache/fc-apps/ $FC_ROOT/fc-apps/ || true
    - cd $FC_ROOT/fc-apps/fc-exploitation && yarn install
    - cd $CI_PROJECT_DIR/quality/fca && yarn install
    - docker-stack fixtures-fca-low
    - cd $CI_PROJECT_DIR
    # Start the NodeJS apps
    - docker-stack start-ci core-fca-low fca-low-front \
      fsa1-low fsa2-low fsa4-low fia1-low fia2-low fia4-low fia5-low \
      exploitation-fca-low
    # Ensure the required apps are running
    - timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://core-fca-low.docker.dev-franceconnect.fr/api/v2/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for core-fca-low..." && sleep 10; done' || (
      (echo 'Cannot connect to core-fca-low') &&
      (docker exec fc_core-fca-low_1 cat /tmp/.pm2/logs/core-fca-low-error-0.log || true) &&
      (docker exec fc_core-fca-low_1 cat /tmp/.pm2/logs/core-fca-low-out-0.log || true) &&
      $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh &&
      exit 1)
    - timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://exploitation-fca-low.docker.dev-franceconnect.fr/login)" != "200" ]];
      do echo "Waiting for exploitation-fca-low..." && sleep 10; done' ||
      (echo 'Cannot connect to exploitation-fca-low' &&
      (docker exec fc_exploitation-fca-low_1 cat /tmp/.pm2/logs/exploitation-fca-low-error-0.log || true) &&
      (docker exec fc_exploitation-fca-low_1 cat /tmp/.pm2/logs/exploitation-fca-low-out-0.log || true) &&
      $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh &&
      exit 1)
    # Starting Cypress Quality checks
    - $CI_PROJECT_DIR/back/scripts/ci/broadcast.sh "Starting Quality checks"
    - cd $CI_PROJECT_DIR/quality/fca
    # Run Visual BDD tests and abort if failed
    - CYPRESS_TEST_ENV=docker yarn test:low:snapshot -c video=${CYPRESS_VIDEO}
    # Run Functional BDD tests  
    - CYPRESS_TEST_ENV=docker yarn test:low:ci -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - CYPRESS_PLATFORM=fca-low CYPRESS_TEST_ENV=docker yarn report:generate
    # Exit if return code equals 1
    - if [ $RETURN_CODE -ne 0 ]; then $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh && (docker cp fc-rp-all:/var/log/nginx /tmp/artifacts-logs || echo "[fc-rp-all] No NginX logs found") && exit $RETURN_CODE; fi
    # Starting Cypress E2E checks
    - $CI_PROJECT_DIR/back/scripts/ci/broadcast.sh "Starting E2E checks"
    - cd $CI_PROJECT_DIR
    - npx cypress${CYPRESS_VERSION} run -c video=${CYPRESS_VIDEO} -P back/instances/core-fca-low || RETURN_CODE=1
    # Extract logs in case of failure
    - if [ $RETURN_CODE -ne 0 ]; then $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh && (docker cp fc-rp-all:/var/log/nginx /tmp/artifacts-logs || echo "[fc-rp-all] No NginX logs found"); fi
    # Exit with return code
    - exit $RETURN_CODE
  interruptible: true
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - back/instances/core-fca-low/cypress/screenshots
      - back/instances/core-fca-low/cypress/videos
      - back/instances/core-fca-low/cypress/logs
      - quality/fca/cypress/reports/cucumber/html-report
      - quality/fca/cypress/snapshots/diff
      - artifacts-logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune -f && docker volume prune -f && docker network prune -f
