include: '/front/.gitlab-build-template.yml'

partners-fcp/build-front:
  extends: .base-build-front
  variables:
    APP: partners-fcp
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\npartners_front_version:"

partners-fcp/tag-front-to-prod:
  extends: .base-tag-front-to-prod
  variables:
    APP: partners-fcp
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\npartners_front_version:"
  needs:
    - job: partners-fcp/build-front
