#!/usr/bin/env bash
set -e

# Define the path directories relative to this script's location
DOCKER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FEDERATION_DIR="$(dirname "${DOCKER_DIR}")"
DOCKER_BASH_DIR="${DOCKER_DIR}/bash"
export PC_DOCKER_REGISTRY="ghcr.io/proconnect-gouv/federation"
export PC_ROOT="$(dirname "${FEDERATION_DIR}")"

source "${DOCKER_BASH_DIR}/utils/index.sh"
source "${DOCKER_BASH_DIR}/config.sh"
source "${DOCKER_BASH_DIR}/commands/index.sh"

## Data initialisation
_command_register "reset-pg" "_hook_admin" "Init postgres Admin"

### Mongo
_command_register "reset-db-core-fca-low" "_reset_db_core_fca_low" ""             # Description to be defined # Deprecated
_command_register "reset-db" "_reset_db_core_fca_low" "Alias to reset-db-core-fca-low" # Backward compatibility entry
_command_register "reset-mongo" "_reset_mongodb" "reset-mongo <mongo-service-name> : Reset given mongodb container"
_command_register "reset-mongo-as-prod" "_reset_mongodb_as_prod" "reset-mongo-as-prod <mongo-service-name> : Reset given mongodb container with production IDPs"
_command_register "mongo" "_mongo_core_shell" "Open mongo shell for core"

## Nodejs apps
_command_register "stop" "_stop" "stop application"
_command_register "stop-all" "_stop_all" "Stop all application for wich containers are up"

## Docker
_command_register "prune" "_prune" "Stop and remove all runing containers"
_command_register "prune-all" "_prune_all" "" # Description to be defined
_command_register "prune-ci" "_prune_ci" "Reset docker for CI runners"
_command_register "up" "_up" "up <stack name> => Launch a stack"
_command_register "exec" "_exec" "exec <container_name> <command> => exec a command inside a container"
_command_register "halt" "_halt" "alt => stop docker-compose and delete containers"
_command_register "switch" "_switch" "Switch to another stack: performs a prune, an up and a start-all"

## General / utils
_command_register "help" "_command_list" "Display this help: help <search term>"
_command_register "compose" "_compose" "Run a docker compose command on project"
_command_register "wait" "wait_for_nodejs" "Wait for a nodejs HTTP service to respond on an URL or try to display logs"
_command_register "llng-configure" "_llng_configure" "Restore LemonLDAP configuration from ./docker/volumes/llng/llng-conf.json dump file"

### Legacy aliases for mongo shell access
_command_register "mongo-script" "_mongo_script" "Execute MongoDB <script> on given <container>: docker-stack mongo-script <container> <script>"

_command_run "$1" "${@:2}"
