include:
  - 'back/instances/**/.gitlab-build.yml'
  - 'back/instances/**/.gitlab-ci.yml'
  - 'back/instances/**/.gitlab-deploy.yml'
  - 'back/instances/**/.gitlab-post-deploy.yml'

variables:
  CYPRESS_CACHE_FOLDER: '${CI_PROJECT_DIR}/.cache/Cypress'
  FC_ROOT: '${CI_BUILDS_DIR}/proconnect'
  YARN_CACHE_FOLDER: ${CI_PROJECT_DIR}/.cache/yarn

#

.var_cache_back_node_modules: &var_cache_back_node_modules
  key:
    files:
      - back/yarn.lock
    prefix: fca_back_node_modules
  #
  fallback_keys:
    - fca_back_node_modules_${CI_DEFAULT_BRANCH}
    - fca_back_node_modules_default
  paths:
    - back/node_modules
  policy: pull

.var_cache_quality_node_modules: &var_cache_quality_node_modules
  key:
    files:
      - quality/yarn.lock
    prefix: fca_quality_node_modules
  #
  fallback_keys:
    - fca_quality_yarn_cache_${CI_DEFAULT_BRANCH}
    - fca_quality_yarn_cache_default
  paths:
    - quality/node_modules
    - ${CYPRESS_CACHE_FOLDER}
  policy: pull

.var_rule_on_merge_request_or_staging: &var_rule_on_merge_request_or_staging
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "fca-staging"'

#

default:
  interruptible: true
  tags:
    - node

#

🧶 back:
  image: node:22.13.0-bullseye
  stage: .pre
  #
  cache:
    - <<: *var_cache_back_node_modules
      policy: pull-push
  rules:
    - <<: *var_rule_on_merge_request_or_staging
      changes:
        - back/yarn.lock
        - back/.gitlab-ci.yml
  #
  before_script:
    - cd ${CI_PROJECT_DIR}/back
    - corepack enable
    - corepack prepare --activate
  script:
    - yarn install --ignore-engines --frozen-lockfile --no-progress

🧶 quality:
  image: node:22.13.0-bullseye
  stage: .pre
  #
  cache:
    - <<: *var_cache_quality_node_modules
      policy: pull-push
  rules:
    - <<: *var_rule_on_merge_request_or_staging
      changes:
        - quality/yarn.lock
        - back/.gitlab-ci.yml
  #
  before_script:
    - cd ${CI_PROJECT_DIR}/quality
    - corepack enable
    - corepack prepare --activate
  script:
    - yarn install --ignore-engines --frozen-lockfile --no-progress
    - yarn cypress install
    - yarn cypress version

#

💅 Lint back:
  image: node:22.13.0-bullseye
  stage: Internal
  #
  cache:
    - <<: *var_cache_back_node_modules
  needs:
    - job: 🧶 back
      optional: true
  rules:
    - <<: *var_rule_on_merge_request_or_staging
  #
  before_script:
    - cd ${CI_PROJECT_DIR}/back
  script:
    - yarn doc
    - git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)
    - yarn generate-oidc-provider-exceptions
    - git --no-pager diff --exit-code || (echo "💥 oidc-provider runtime exceptions diff detected 💥" && exit 1)
    - yarn lint
    - yarn prettier
    - yarn tsc --noEmit

🧪 Test back:
  image: node:22.13.0-bullseye
  stage: Internal
  #
  cache:
    - <<: *var_cache_back_node_modules
  coverage: '/Global coverage is: \[([\d\.]+)%\]/'
  interruptible: true
  needs:
    - job: 🧶 back
      optional: true
  rules:
    - <<: *var_rule_on_merge_request_or_staging
  #
  before_script:
    - cd ${CI_PROJECT_DIR}/back
    - apt-get update && apt-get install -y bc
  script:
    - yarn test --coverage
    - ${CI_PROJECT_DIR}/coverage.sh

💅 Lint quality:
  image: node:22.13.0-bullseye
  stage: Internal
  #
  cache:
    - <<: *var_cache_quality_node_modules
  needs:
    - job: 🧶 quality
      optional: true
  rules:
    - <<: *var_rule_on_merge_request_or_staging
  #
  before_script:
    - cd ${CI_PROJECT_DIR}/quality
  script:
    - yarn lint
    - yarn prettier
    - yarn tsc --noEmit
