variables:
  FC_ROOT: '$CI_BUILDS_DIR/france-connect'
  PROXY_EXPLOITATION: 'http://$EXPLOITATION_PROXY_HOST:$EXPLOITATION_PROXY_PORT'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

back:
  image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
  stage: 'Code quality'
  tags:
    - node
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "staging"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "staging"'
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      - back/node_modules/
      - quality/node_modules/
  script:
    # Back folder
    - cd back/
    - yarn install --ignore-engines
    - yarn doc
    - git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)
    - yarn lint
    - yarn prettier
    - yarn test --coverage
    - ../coverage.sh
    # Quality folder
    - cd $CI_PROJECT_DIR/quality
    - yarn install --ignore-engines
    - yarn lint
    - yarn prettier
    - yarn tsc --noEmit
  coverage: '/Global coverage is: \[([\d\.]+)%\]/'
  interruptible: true

build-cache:
  image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
  tags:
    - node
  cache:
    key: ${CI_PROJECT_ID}
    policy: push
    paths:
      # Back
      - back/node_modules/
      # Front
      - front/node_modules/
      - front/instances/agent-connect/node_modules/
      - front/instances/exploit-fca-low/node_modules/
      - front/instances/exploit-fcp-high/node_modules/
      - front/instances/partners-fca/node_modules/
      - front/instances/partners-fcp/node_modules/
      - front/instances/user-dashboard/node_modules/
      # Quality
      - quality/node_modules/
      # Fc-apps
      - cache/fc-apps/fc-exploitation/node_modules/
      - cache/fc-apps/fc-stats/node_modules/
      - cache/fc-apps/fc-support/node_modules/
      - cache/fc-apps/fc-workers/node_modules/
      - cache/fc-apps/node_modules/
      - cache/fc-apps/shared/node_modules/
      # core-legacy
      - cache/core-legacy/node_modules/
      - cache/core-legacy/projects/fc/core/node_modules/
      - cache/core-legacy/projects/fc/fc-commons/node_modules/
      - cache/core-legacy/projects/partenaires/node_modules/
      # Cypress cache
      - cache/Cypress
  stage: 'Cache'
  script:
    - cd $CI_PROJECT_DIR/back && yarn install --ignore-engines
    - cd $CI_PROJECT_DIR/front && yarn install
    - cd $CI_PROJECT_DIR/quality && yarn install --ignore-engines
    - git clone -b $FC_APPS_VERSION --depth 1 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-apps.git $CI_PROJECT_DIR/cache/fc-apps
    - cd $CI_PROJECT_DIR/cache/fc-apps && yarn install
    - git clone -b $FC_LEGACY_VERSION --depth 1 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/core-legacy.git $CI_PROJECT_DIR/cache/core-legacy
    - cd $CI_PROJECT_DIR/cache/core-legacy && yarn install
  dependencies: []
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'

include:
  - 'back/instances/**/.gitlab-build.yml'
  - 'back/instances/**/.gitlab-ci.yml'
  - 'back/instances/**/.gitlab-deploy.yml'
  - 'back/instances/**/.gitlab-post-deploy.yml'
  - '/back/.gitlab-post-deploy.yml'
