stages:
  - 'Unit tests'
  - 'End to end'

global:
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  tags:
    - nodejs
  cache:
    key: "${CI_PROJECT_ID}-unit"
    policy: pull-push
    paths:
      - back/yarn.lock
      - back/node_modules/
  stage: 'Unit tests'
  script:
    - cd back/
    - yarn install
    - yarn lint
    - yarn prettier
    - yarn test --coverage
    - ./scripts/coverage.sh
  coverage: '/Global coverage is: \[([\d\.]+)%\]/'

include:
  - '/back/instances/core-fcp-high/.gitlab-ci.yml'
  - '/back/instances/core-fca-high/.gitlab-ci.yml'
  - '/back/instances/eidas-bridge/.gitlab-ci.yml'
