.base-build:
  stage: 'Build Back'
  image: ${BUILD_IMAGE}
  tags:
    - build
  only:
    - tags
  when: manual
  environment:
    name: build
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
  services:
    - name: docker:25.0.5-dind
      command: ['--experimental']
  before_script:
    - echo "$INFRA_REGISTRY_PASS" | docker login $INFRA_REGISTRY --username $INFRA_REGISTRY_USER --password-stdin
    - rm -rf $FC_ROOT/fc-docker
    - git clone -b 30-build-partners --single-branch https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-docker.git $FC_ROOT/fc-docker
  script:
    - cd $FC_ROOT/fc-docker
    - ./build.sh $APP $RELEASE_VERSION
    - echo -e "\e[1;34m$MSG $RELEASE_VERSION\e[0m"

.base-tag-to-prod:
  stage: 'Tag Back'
  image: ${BUILD_IMAGE}
  tags:
    - build
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /RC.$/
      when: manual
      allow_failure: false
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    PATCH_VERSION: 0
    RELEASE_VERSION: $CI_COMMIT_REF_NAME
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:25.0.5-dind
      command: ['--experimental']
  before_script:
    - echo "$INFRA_REGISTRY_PASS" | docker login $INFRA_REGISTRY --username $INFRA_REGISTRY_USER --password-stdin
    - PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}
  script:
    - while docker manifest inspect $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION; [[ $? -eq 0 ]];
      do PATCH_VERSION=$((PATCH_VERSION+1)); PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}; done
    - export PROD_RELEASE_VERSION
    - docker pull $INFRA_REGISTRY/$DOCKER_IMAGE:$RELEASE_VERSION
    - docker tag $INFRA_REGISTRY/$DOCKER_IMAGE:$RELEASE_VERSION $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION
    - docker push $INFRA_REGISTRY/$DOCKER_IMAGE:$PROD_RELEASE_VERSION
    - echo -e "\e[1;34m$MSG $PROD_RELEASE_VERSION\e[0m"
    - >
      curl -s -X POST --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.dev-franceconnect.fr/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${PROD_RELEASE_VERSION}&ref=${RELEASE_VERSION}"
  environment:
    name: build
