variables:
  CYPRESS_CACHE_FOLDER: '${CI_PROJECT_DIR}/cache/Cypress'
  FC_ROOT: '$CI_BUILDS_DIR/france-connect'
  GIT_DEPTH: 0
  PC_APPS_VERSION: '${PC_APPS_VERSION:-fca-staging}'
  PROXY_EXPLOITATION: 'http://$EXPLOITATION_PROXY_HOST:$EXPLOITATION_PROXY_PORT'
  YARN_CACHE_FOLDER: ${CI_BUILDS_DIR}/.yarn-cache

back:
  image: node:22.12.0-bullseye
  stage: 'Code quality'
  tags:
    - node
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "fca-staging"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "fca-staging"'
  cache:
    - key:
        files:
          - back/yarn.lock
        prefix: fca_back_node_modules
      paths:
        - back/node_modules
  before_script:
    - cd ${CI_PROJECT_DIR}/back
    - corepack enable
    - corepack prepare --activate
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn doc
    - git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)
    - yarn lint
    - yarn prettier
    - yarn generate-oidc-provider-exceptions
    - git --no-pager diff --exit-code || (echo "💥 oidc-provider runtime exceptions diff detected 💥" && exit 1)
    - yarn test --coverage
    - apt-get update && apt-get install -y bc
    - ${CI_PROJECT_DIR}/coverage.sh
  coverage: '/Global coverage is: \[([\d\.]+)%\]/'
  interruptible: true

quality:
  image: node:22.12.0-bullseye-slim
  stage: 'Code quality'
  tags:
    - node
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "staging"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "staging"'
  cache:
    - key:
        files:
          - quality/yarn.lock
        prefix: fca_quality_node_modules
      paths:
        - quality/node_modules
        - ${CYPRESS_CACHE_FOLDER}
  before_script:
    - cd ${CI_PROJECT_DIR}/quality
    - corepack enable
    - corepack prepare --activate
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - cd ${CI_PROJECT_DIR}/quality/fca
    - yarn lint
    - yarn prettier
    - yarn tsc --noEmit
  interruptible: true

build-cache:
  image: node:22.12.0-bullseye-slim
  tags:
    - node
  cache:
    key: ${CI_PROJECT_ID}-fca
    policy: push
    paths:
      # Back
      - back/node_modules/
      # Quality
      - quality/node_modules/
      # Fc-apps
      - cache/fc-apps/fc-exploitation/node_modules/
      - cache/fc-apps/fc-support/node_modules/
      - cache/fc-apps/fc-workers/node_modules/
      - cache/fc-apps/node_modules/
      - cache/fc-apps/shared/node_modules/
      # Cypress cache
      - cache/Cypress
  stage: 'Cache'
  script:
    - cd $CI_PROJECT_DIR/back && yarn install --frozen-lockfile --ignore-engines
    - cd $CI_PROJECT_DIR/quality && yarn install --frozen-lockfile
    - git clone -b $PC_APPS_VERSION --depth 1 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-apps.git $CI_PROJECT_DIR/cache/fc-apps
    - cd $CI_PROJECT_DIR/cache/fc-apps && yarn install --frozen-lockfile
  dependencies: []
  interruptible: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "fca-staging"'

include:
  - 'back/instances/**/.gitlab-build.yml'
  - 'back/instances/**/.gitlab-ci.yml'
  - 'back/instances/**/.gitlab-deploy.yml'
  - 'back/instances/**/.gitlab-post-deploy.yml'
  - '/back/.gitlab-post-deploy.yml'
