.base-build:
  stage: 'Build Back'
  image: ${BUILD_IMAGE}
  tags:
    - build
  only:
    - tags
  environment:
    name: build
  variables:
    GIT_STRATEGY: none
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
  services:
    - name: docker:27-dind
  before_script:
    - rm -rf $FC_ROOT/fc-docker
    - git clone -b $FC_DOCKER_VERSION --single-branch https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/proconnect/fc-docker.git $FC_ROOT/fc-docker
  script:
    - cd $FC_ROOT/fc-docker
    - export NODE_VERSION=v22.13.0
    - ./build.sh $APP $RELEASE_VERSION
    - echo -e "\e[1;34m$MSG $RELEASE_VERSION\e[0m"
   new:
    - hello