stages:
  - 'Unit tests'
  - 'End to end'

global:
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  stage: 'Unit tests'
  script:
    - cd back/
    - yarn install
    - yarn lint
    - yarn prettier
    - yarn test --coverage
    - ./scripts/coverage.sh
  coverage: '/Global coverage is: \[([\d\.]+)%\]/'

include:
  - '/back/instances/core-fcp-high/.gitlab-ci.yml'
