include: '/back/.gitlab-build-template.yml'

partners/partners-back-build-image:
  extends: .base-build
  variables:
    APP: partners-back
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\npartners_back_version:"

partners/partners-back-tag-to-prod-image: 
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: partners-back
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\npartners_back_version:"
  needs:
    - job: partners/partners-back-build-image