export enum ErrorCode {
  NO_IDP = 1,
  INVALID_IDENTITY = 6,
  NO_SESSION_ID = 9,
  AGENT_NOT_FOUND = 15,
  IDP_HINT_NOT_FOUND = 16,
  DISABLED_PROVIDER = 17,
  ACR_NOT_SATISFIED = 20,
  LOGIN_REQUIRED = 21,
  BLOCKED_ACCOUNT = 24,
  UNAUTHORIZED_EMAIL = 25,
  MISCONFIGURED_PROVIDER = 26,
}
