export enum Routes {
  ACCESSIBILITY = "/accessibilite",
  DEFAULT = "/",
  HEALTHCHECK_LIVE = "/livez",
  HEALTHCHECK_READY = "/readyz",
  HEALTHCHECK_READY_CHECK = "/readyz/:check",
  INTERACTION = "/interaction/:uid",
  INTERACTION_VERIFY = "/interaction/:uid/verify",
  INTERACTION_ERROR = "/interaction/:uid/error",
  PROCEED_TO_CROSS_DEVICE_AUTHENTICATION = "/proceed-to-cross-device-authentication",
  PROCEED_TO_IDP = "/proceed-to-idp",
  REDIRECT_TO_IDP = "/redirect-to-idp",
  REVIEW_CROSS_DEVICE_AUTHENTICATION_REQUESTS = "/xda",
  IDENTITY_PROVIDER_SELECTION = "/identity-provider-selection",
  RIE_IDP_WARNING = "/rie-idp-warning",
  VERIFY_EMAIL = "/verify-email",
  VERIFY_EMAIL_RESEND = "/verify-email/resend",
  OIDC_CALLBACK = "/oidc-callback",
  OIDC_LOGOUT_CALLBACK = "/client/logout-callback",
}
