quality-core-fcp-high:
  stage: 'Post-deploy'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - docker
  # only:
  #   - tags
  # à activer une fois fini
  script:
    - cd quality/fcp
    - yarn install
    - CYPRESS_TEST_ENV=integ01 yarn test:high || true
    - yarn report:prepare
    - CYPRESS_PLATFORM=fcp-high CYPRESS_TEST_ENV=integ01 yarn report:generate
  artifacts:
    expire_in: 1 hrs
    paths:
      - $CI_PROJECT_DIR/quality/fcp/cypress/reports/cucumber/report.html
  environment:
    name: integ01
    url: https://auth.integ01.dev-franceconnect.fr
  when: manual
