review-fcp-high:
  stage: 'Review'
  image: ${DEPLOY_IMAGE}
  tags:
    - recette
  only:
    - merge_requests
    - staging
  variables:
    GIT_STRATEGY: none
  script:
    - chmod og= $RECETTE_SSH_KEY
    - ssh -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER "sh /data/fcp-high/start $CI_COMMIT_REF_NAME $FC_APPS_VERSION $CI_JOB_TOKEN $CI_REGISTRY $CI_OPEN_MERGE_REQUESTS"
  resource_group: recette
  dependencies: []
  environment:
    name: recette
    url: https://recette.dev-franceconnect.fr
    on_stop: stop-fcp-high
    auto_stop_in: 1 hour
  when: manual

stop-fcp-high:
  stage: 'Review'
  image: ${DEPLOY_IMAGE}
  tags:
    - recette
  variables:
    GIT_STRATEGY: none
  script:
    - chmod og= $RECETTE_SSH_KEY
    - ssh -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER "sh /data/teardown core-fcp-high"
    - scp -i $RECETTE_SSH_KEY -o StrictHostKeyChecking=no fcapp@$RECETTE_SERVER:/data/fcp-high/workspace/fc/docker/volumes/log/*.log .
  artifacts:
    expire_in: 1 hrs
    paths:
      - $CI_PROJECT_DIR
  resource_group: recette
  dependencies: []
  environment:
    name: recette
    action: stop
  only:
    - merge_requests
    - staging
  when: manual

quality-fcp-high-recette:
  stage: 'Review'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - cypress
  only:
    - merge_requests
    - staging
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      - quality/node_modules/
  variables:
    no_proxy: ""
  before_script:
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
  script:
    - unset EXPLOIT_USER_NAME && unset EXPLOIT_USER_PASS && unset EXPLOIT_USER_TOTP
    - cd quality/fcp && yarn install
    - CYPRESS_TEST_ENV=recette yarn test:high:ci -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - CYPRESS_PLATFORM=fcp-high CYPRESS_TEST_ENV=recette yarn report:generate
    - exit $RETURN_CODE
  resource_group: recette
  dependencies: []
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - $CI_PROJECT_DIR/quality/fcp/cypress/reports/cucumber/html-report
  environment:
    name: recette
    url: https://recette.dev-franceconnect.fr
  when: manual
