fcp-and-eidas-high:
  stage: 'End to end'
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  timeout: 1h
  tags:
    - cypress
  variables:
    TZ: 'Europe/Paris'
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      # Back
      - back/node_modules/
      # Front
      - front/node_modules/
      - front/apps/agent-connect/node_modules/
      - front/apps/exploit-fca-low/node_modules/
      - front/apps/exploit-fcp-high/node_modules/
      - front/apps/partners-fca/node_modules/
      - front/apps/partners-fcp/node_modules/
      - front/apps/user-dashboard/node_modules/
      # Quality
      - quality/node_modules/
      # Fc-apps
      - cache/fc-apps/fc-exploitation/node_modules/
      - cache/fc-apps/fc-stats/node_modules/
      - cache/fc-apps/fc-support/node_modules/
      - cache/fc-apps/fc-workers/node_modules/
      - cache/fc-apps/node_modules/
      - cache/fc-apps/shared/node_modules/
      # Cypress
      - $CYPRESS_CACHE_FOLDER
  before_script:
    # Ensure a clean docker environnement
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - RETURN_CODE=0
    # Shallow clone depth 1 FC-APP repository
    - rm -rf $FC_ROOT/fc-apps
    - git clone -b $FC_APPS_VERSION --depth 1 https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.dev-franceconnect.fr/france-connect/fc-apps.git $FC_ROOT/fc-apps
    # Bind sources in docker volumes
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc
    - ln -s $FC_ROOT/fc/front/apps/user-dashboard $FC_ROOT/fc/docker/volumes/src/user-dashboard
    - ln -s $FC_ROOT/fc-apps $FC_ROOT/fc/docker/volumes/src/fc-apps
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do cd $mock && git fetch && git checkout -f origin/master && git clean -df && echo "Installing depedencies for $(/usr/bin/basename $mock)" && npm install; ln -sfn $mock $FC_ROOT/fc/docker/volumes/src; done
    # Return to project directory 
    - wait
    - cd $CI_PROJECT_DIR
  script:
    # Up the docker-stack with minimal requirement
    - docker-stack up all-eidas-high
    - docker exec fc_core-fcp-high_1 bash -c "yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION"
    - docker-stack dep core-fcp-high
    - rsync -a $CI_PROJECT_DIR/cache/fc-apps/ $FC_ROOT/fc-apps/ || true
    - cd $FC_ROOT/fc-apps/fc-exploitation && yarn install
    - cd $CI_PROJECT_DIR/quality/fcp && yarn install
    - docker-stack fixtures-fcp-high
    - cd $CI_PROJECT_DIR
    # Start the NodeJS apps
    - docker-stack start-ci \
      csmr-hsm rnipp \
      fsp1-high fsp2-high fsp5-high fsp6-high \
      fip1-high fip2-high fip13-high fip14-high fip15-high fip16-high fip17-high fip18-high fip19-high fip20-high \
      core-fcp-high \
      exploitation-high \
      eidas-bridge
    # Ensure the required apps are running
    - timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for core-fcp-high..." && sleep 10; done' || (
      (echo 'Cannot connect to core-fcp-high') &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-error-0.log || true) &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-out-0.log || true) &&
      $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh &&
      exit 1)
    - timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://exploitation-high.docker.dev-franceconnect.fr/login)" != "200" ]];
      do echo "Waiting for exploitation-high..." && sleep 10; done' ||
      (echo 'Cannot connect to exploitation-high' &&
      (docker exec fc_exploitation-high_1 cat /tmp/.pm2/logs/exploitation-high-error-0.log || true) &&
      (docker exec fc_exploitation-high_1 cat /tmp/.pm2/logs/exploitation-high-out-0.log || true) &&
      $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh &&
      exit 1)
    - timeout 180 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://eidas-bridge.docker.dev-franceconnect.fr/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for eidas-bridge..." && sleep 10; done' || (
      (echo 'Cannot connect to eidas-bridge') &&
      (docker exec fc_eidas-bridge_1 cat /tmp/.pm2/logs/eidas-bridge-error-0.log || true) &&
      (docker exec fc_eidas-bridge_1 cat /tmp/.pm2/logs/eidas-bridge-out-0.log || true) &&
      $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh &&
      exit 1)
    # Starting Cypress Quality checks
    - $CI_PROJECT_DIR/back/scripts/ci/broadcast.sh "Starting Quality checks"
    - cd $CI_PROJECT_DIR/quality/fcp
    # Run Visual BDD tests and abort if failed
    - CYPRESS_TEST_ENV=docker yarn test:high:snapshot -c video=${CYPRESS_VIDEO}
    # Run Functional BDD tests
    - CYPRESS_TEST_ENV=docker yarn test:high:ci -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - CYPRESS_PLATFORM=fcp-high CYPRESS_TEST_ENV=docker yarn report:generate
    # Exit if return code equals 1
    - if [ $RETURN_CODE -ne 0 ]; then $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh && (docker cp fc-rp-all:/var/log/nginx /tmp/artifacts-logs || echo "[fc-rp-all] No NginX logs found") && exit $RETURN_CODE; fi
    # Starting Cypress E2E checks
    - $CI_PROJECT_DIR/back/scripts/ci/broadcast.sh "Starting E2E checks"
    - cd $CI_PROJECT_DIR
    - npx cypress${CYPRESS_VERSION} run -c video=${CYPRESS_VIDEO} -P back/instances/core-fcp-high || RETURN_CODE=1
    # Extract logs in case of failure
    - if [ $RETURN_CODE -ne 0 ]; then $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh && (docker cp fc-rp-all:/var/log/nginx /tmp/artifacts-logs || echo "[fc-rp-all] No NginX logs found") && exit $RETURN_CODE; fi
    # Starting eIDAS E2E checks
    - $CI_PROJECT_DIR/back/scripts/ci/broadcast.sh "Starting eIDAS E2E checks"
    - cd $CI_PROJECT_DIR
    - npx cypress${CYPRESS_VERSION} run -c video=${CYPRESS_VIDEO} -P back/instances/eidas-bridge || RETURN_CODE=1
    # Extract logs in case of failure
    - if [ $RETURN_CODE -ne 0 ]; then $CI_PROJECT_DIR/back/scripts/ci/extract-pm2-logs.sh && (docker cp fc-rp-all:/var/log/nginx /tmp/artifacts-logs || echo "[fc-rp-all] No NginX logs found"); fi
    # Exit with return code
    - exit $RETURN_CODE
  interruptible: true
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - $CI_PROJECT_DIR/back/instances/core-fcp-high/cypress/screenshots
      - $CI_PROJECT_DIR/back/instances/core-fcp-high/cypress/videos
      - $CI_PROJECT_DIR/back/instances/core-fcp-high/cypress/logs
      - $CI_PROJECT_DIR/quality/fcp/cypress/reports/cucumber/html-report
      - $CI_PROJECT_DIR/quality/fcp/cypress/snapshots/diff
      - $CI_PROJECT_DIR/artifacts-logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune -f && docker volume prune -f && docker network prune -f
