quality-core-fcp-high-release:
  stage: 'Post-deploy'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - docker
  only:
    - tags
  when: manual
  environment:
    name: integ01
    url: https://auth.integ01.dev-franceconnect.fr
  variables:
    FC_ROOT: '$CI_BUILDS_DIR/france-connect'
  before_script:
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
  # Build the nginx proxy to access /integ01/fcp.html
    - docker-stack up rp-all
    - cd quality/fcp
    - yarn install
    - CYPRESS_TEST_ENV=integ01 yarn test:high:chrome-desktop -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - CYPRESS_PLATFORM=fcp-high CYPRESS_TEST_ENV=integ01 yarn report:generate
    - exit $RETURN_CODE
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - $CI_PROJECT_DIR/quality/fcp/cypress/reports/cucumber/html-report  
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
