include: '/back/.gitlab-build-template.yml'

fc+/core-build-image:
  extends: .base-build
  variables:
    APP: core-v2
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\ncore_v2_version:"

fc+/core-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: core-fcp-high
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\ncore_v2_version:"
  needs:
    - job: fc+/core-build-image

fc+/fip1v2-build-image:
  extends: .base-build
  variables:
    APP: mock-identity-provider-fcp-high
    MSG: "environments/outscale-tools/group_vars/all/versions.yml\nfip1v2_version:"

fc+/fip1v2-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: mock-identity-provider-fcp-high
    MSG: "environments/outscale-tools/group_vars/all/versions.yml\nfip1v2_version:"
  needs:
    - job: fc+/fip1v2-build-image

fc+/fsp1v2-build-image:
  extends: .base-build
  variables:
    APP: mock-service-provider-fcp-high
    MSG: "environments/outscale-tools/group_vars/all/versions.yml\nfsp1v2_version:"

fc+/fsp1v2-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: mock-service-provider-fcp-high
    MSG: "environments/outscale-tools/group_vars/all/versions.yml\nfsp1v2_version:"
  needs:
    - job: fc+/fsp1v2-build-image

fc+/csmr-hsm-build-image:
  extends: .base-build
  variables:
    APP: csmr-hsm-high
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\ncsmr_hsm_version:"

fc+/csmr-hsm-tag-to-prod-image:
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: csmr-hsm-high
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\ncsmr_hsm_version:"
  needs:
    - job: fc+/csmr-hsm-build-image
