core-fcp-high:
  stage: 'End to end'
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
  tags:
    - docker
  variables:
    FC_ROOT: '$CI_BUILDS_DIR/france-connect'
    TZ: 'Europe/Paris'
  cache:
    key: '${CI_PROJECT_ID}'
    policy: pull
    paths:
      - back/node_modules/
  before_script:
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc
    - ln -s $FC_ROOT/fc/front/apps/user-dashboard $FC_ROOT/fc/docker/volumes/src/user-dashboard
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do ln -s $mock $FC_ROOT/fc/docker/volumes/src; done
  script:
    - docker-stack up all-fcp-high
    - docker-stack dep core-fcp-high
    - docker-stack start \
      csmr-hsm rnipp \
      fsp1-high fsp2-high fsp5-high fsp6-high \
      fip1-high fip2-high fip13-high fip14-high fip15-high fip16-high fip17-high fip18-high fip19-high fip20-high \
      core-fcp-high
    # ## -- Build like for prod
    #- docker-stack exec fsp1-high yarn build mock-service-provider-fcp-high # Will build for fsp2-high as well
    #- docker-stack exec core-fcp-high yarn build core-fcp-high
    #- docker-stack exec csmr-hsm yarn build csmr-hsm-high
    # ## -- Launch like prod
    #- docker-stack exec fsp1-high yarn start:prod:mock-service-provider-fcp-high &
    #- docker-stack exec fsp2-high yarn start:prod:mock-service-provider-fcp-high &
    #- docker-stack exec core-fcp-high yarn start:prod:core-fcp-high &
    #- docker-stack exec csmr-hsm yarn start:prod:csmr-hsm-high &
    # Starting Cypress
    - timeout 120 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for core-fcp-high..." && sleep 10; done' || (
      (echo 'Cannot connect to core-fcp-high') &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-error-0.log || true) &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-out-0.log || true) &&
      exit 1)
    - npx cypress${CYPRESS_VERSION} run -c video=${CYPRESS_VIDEO} -P back/instances/core-fcp-high || (
      (docker cp fc_core-fcp-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_csmr-hsm_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_rnipp_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip1-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip13-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip14-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip15-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip16-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip17-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip18-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip19-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fip20-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fsp1-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fsp2-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fsp5-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc_fsp6-high_1:/tmp/.pm2/logs back/instances/core-fcp-high/cypress || true) &&
      (docker cp fc-rp-all:/var/log/nginx back/instances/core-fcp-high/cypress/logs || true) &&
      exit 1)
  interruptible: true
  artifacts:
    expire_in: 1 hrs
    when: on_failure
    paths:
      - back/instances/core-fcp-high/cypress/screenshots
      - back/instances/core-fcp-high/cypress/videos
      - back/instances/core-fcp-high/cypress/logs
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
