quality-fcp-high-docker:
  stage: 'End to end'
  image: ${E2E_DOCKER_IMAGE}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"'
      when: manual
      allow_failure: false
  tags:
    - docker
  variables:
    FC_ROOT: '$CI_BUILDS_DIR/france-connect'
    TZ: 'Europe/Paris'
  cache:
    key: '${CI_PROJECT_ID}'
    policy: pull
    paths:
      - back/node_modules/
  before_script:
    - echo "FC_DOCKER_VERSION=$FC_DOCKER_VERSION"
    - if [ "$(docker ps -a -q -f name=^fc-rp-all)" ]; then bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt && docker container prune -f && docker volume prune -f; fi
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - if [[ ! -d $FC_ROOT/mocks ]]; then cp -R /var/www/mocks $FC_ROOT/; fi
    - ln -s $CI_PROJECT_DIR $FC_ROOT/fc/docker/volumes/src/fc
    - ln -s $FC_ROOT/fc/front/apps/user-dashboard $FC_ROOT/fc/docker/volumes/src/user-dashboard
    - ln -s $FC_ROOT/fc-apps $FC_ROOT/fc/docker/volumes/src/fc-apps
    - for mock in `find $FC_ROOT/mocks -maxdepth 1 -mindepth 1 -type d`; do ln -s $mock $FC_ROOT/fc/docker/volumes/src; done
  script:
    - docker-stack up all-fcp-high
    - docker-stack dep core-fcp-high exploitation-high
    - docker-stack fixtures-v2
    - docker-stack start csmr-hsm rnipp fsp1-high fsp2-high fip1-high core-fcp-high exploitation-high
    # ## -- Build like for prod
    #- docker-stack exec fsp1-high yarn build mock-service-provider-high # Will build for fsp2-high as well
    #- docker-stack exec core-fcp-high yarn build core-fcp-high
    #- docker-stack exec csmr-hsm yarn build csmr-hsm-high
    # ## -- Launch like prod
    #- docker-stack exec fsp1-high yarn start:prod:mock-service-provider-high &
    #- docker-stack exec fsp2-high yarn start:prod:mock-service-provider-high &
    #- docker-stack exec core-fcp-high yarn start:prod:core-fcp-high &
    #- docker-stack exec csmr-hsm yarn start:prod:csmr-hsm-high &
    # Starting Cypress
    - timeout 60 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/.well-known/openid-configuration)" != "200" ]];
      do echo "Waiting for core-fcp-high..." && sleep 10; done' || (
      (echo 'Cannot connect to core-fcp-high') &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-error-0.log || true) &&
      (docker exec fc_core-fcp-high_1 cat /tmp/.pm2/logs/core-fcp-high-out-0.log || true) &&
      exit 1)
    - timeout 100 bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' https://exploitation-high.docker.dev-franceconnect.fr/login)" != "200" ]];
      do echo "Waiting for exploitation-high..." && sleep 10; done' ||
      (echo 'Cannot connect to exploitation-high' &&
      (docker exec fc_exploitation-high_1 cat /tmp/.pm2/logs/exploitation-high-error-0.log || true) &&
      (docker exec fc_exploitation-high_1 cat /tmp/.pm2/logs/exploitation-high-out-0.log || true) &&
      exit 1)
    - cd $CI_PROJECT_DIR/quality/fcp
    - yarn install
    - CYPRESS_TEST_ENV=docker yarn test:high:chrome-desktop -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report:prepare
    - CYPRESS_PLATFORM=fcp-high CYPRESS_TEST_ENV=docker yarn report:generate
    - exit $RETURN_CODE
  interruptible: true
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - $CI_PROJECT_DIR/quality/fcp/cypress/reports/cucumber/html-report
  after_script:
    - bash $CI_BUILDS_DIR/france-connect/fc/docker/docker-stack halt
    - docker container prune --force && docker volume prune -f
