include: '/front/.gitlab-build-template.yml'

partners/build-front:
  extends: .base-build-front
  variables:
    APP: partners
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\nupartners:"

partners/tag-front-to-prod:
  extends: .base-tag-front-to-prod
  variables:
    APP: partners
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\nupartners:"
  needs:
    - job: partners/build-front
