export const Fsa1ServiceProviderDocument = {
  active: true,
  client_id: 'fsa_fsa1_low_client_id',
  client_secret:
    '+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=',
  id_token_signed_response_alg: 'HS256',
  key: 'fsa_fsa1_low_key',
  name: 'FSA - FSA1-LOW',
  post_logout_redirect_uris: ['https://fsa1-low.docker.dev-franceconnect.fr/'],
  redirect_uris: ['https://fsa1-low.docker.dev-franceconnect.fr/oidc-callback'],
  scopes: [
    'uid',
    'openid',
    'given_name',
    'email',
    'phone',
    'organizational_unit',
    'siren',
    'siret',
    'usual_name',
    'belonging_population',
    'chorusdt',
    'idp_id',
    'idp_acr',
    'groups',
    'custom',
  ],
  title: 'FSA - FSA1-LOW Title',
  type: 'public',
};
