include: '/back/.gitlab-build-template.yml'

csmr-config-sandbox-low/csmr-config-sandbox-low-build-image:
  extends: .base-build
  variables:
    APP: csmr-config-sandbox-low
    MSG: "environments/pa4-integ/group_vars/all/versions.yml\ncsmr_config_sandbox_low_version:"

csmr-config-sandbox-low/csmr-config-sandbox-low-back-tag-to-prod-image: 
  extends: .base-tag-to-prod
  variables:
    DOCKER_IMAGE: csmr-config-sandbox-low
    MSG: "environments/pa4-preprod/group_vars/all/versions.yml\nenvironments/pa4-prod/group_vars/all/versions.yml\ncsmr_config_sandbox_low_version:"
  needs:
    - job: csmr-config-sandbox-low/csmr-config-sandbox-low-build-image