include: '/back/.gitlab-build-template.yml'

fca/bridge-http-proxy-rie-build-image:
  extends: .base-build
  environment:
    name: build-fca
  variables:
    APP: bridge-http-proxy-rie
    MSG: "environments/nubo12-fca-integ/group_vars/all/versions.yml\nbridge_http_proxy_rie_version:"

fca/bridge-http-proxy-rie-tag-to-prod-image:
  extends: .base-tag-to-prod
  environment:
    name: build-fca
  variables:
    DOCKER_IMAGE: bridge-http-proxy-rie
    MSG: "environments/nubo12-fca-prod/group_vars/all/versions.yml\nbridge_http_proxy_rie_version:"
  needs:
    - job: fca/bridge-http-proxy-rie-build-image
