.base-build-front:
  stage: 'Build Front'
  image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
  tags:
    - build-fc
  only:
    - tags
  when: manual
  environment:
    name: build
  variables:
    PACKAGE: ${CI_COMMIT_REF_NAME}.tar.gz
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
  script:
    - cd front
    - yarn install --frozen-lockfile
    - yarn build $APP
    - tar zcvf ${CI_PROJECT_DIR}/${PACKAGE} -C ${CI_PROJECT_DIR}/front/instances/${APP}/build/ .
    - >
      curl --header "JOB-TOKEN:$CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/${PACKAGE} "${INFRA_PACKAGE_REGISTRY}/${APP}/${CI_COMMIT_REF_NAME}/${PACKAGE}"
    - echo -e "\e[1;34m$MSG $RELEASE_VERSION\e[0m"

.base-tag-front-to-prod:
  stage: 'Tag Front'
  image: ${BUILD_IMAGE}
  tags:
    - build-fc
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /RC.$/
      when: manual
      allow_failure: false
  environment:
    name: build
  variables:
    GIT_STRATEGY: none
    PACKAGE: ${CI_COMMIT_REF_NAME}.tar.gz
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
    PATCH_VERSION: 0
  before_script:
    - PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}
  script:
    - >
      curl --header "JOB-TOKEN:$CI_JOB_TOKEN" "${INFRA_PACKAGE_REGISTRY}/${APP}/${RELEASE_VERSION}/${PACKAGE}" --output ${PACKAGE}
    - while [[ $(curl --header "JOB-TOKEN:$CI_JOB_TOKEN" -I -s -o /dev/null -w "%{http_code}" "${INFRA_PACKAGE_REGISTRY}/${APP}/${PROD_RELEASE_VERSION}/${PROD_RELEASE_VERSION}.tar.gz") == 200 ]];
      do PATCH_VERSION=$((PATCH_VERSION+1)); PROD_RELEASE_VERSION=${RELEASE_VERSION::-3}.${PATCH_VERSION}; done
    - export PROD_RELEASE_VERSION
    - export PROD_PACKAGE=${PROD_RELEASE_VERSION}.tar.gz
    - mv ${PACKAGE} ${PROD_PACKAGE}
    - >
      curl --header "JOB-TOKEN:$CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/${PROD_PACKAGE} "${INFRA_PACKAGE_REGISTRY}/${APP}/${PROD_RELEASE_VERSION}/${PROD_PACKAGE}"
    - echo -e "\e[1;34m$MSG $PROD_RELEASE_VERSION\e[0m"
    - >
      curl -s -X POST --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.dev-franceconnect.fr/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${PROD_RELEASE_VERSION}&ref=${RELEASE_VERSION}"
