quality-fcp-low-release:
  stage: 'Post-deploy'
  image: ${E2E_DOCKER_IMAGE}
  tags:
    - cypress
  only:
    - tags
  when: manual
  needs: []
  environment:
    name: integ01
    url: https://fcp-low.integ01.dev-franceconnect.fr
  variables:
    CYPRESS_PLATFORM: 'fcp-low'
    CYPRESS_TEST_ENV: 'integ01'
    CYPRESS_EXPLOIT_USER_NAME: $EXPLOIT_FCP_LEGACY_USER
    CYPRESS_EXPLOIT_USER_PASS: $EXPLOIT_FCP_LEGACY_PWD
    CYPRESS_EXPLOIT_USER_TOTP: $EXPLOIT_FCP_LEGACY_TOTP
    CYPRESS_INTERNAL_BROWSER_CONNECT_TIMEOUT: 120000
  cache:
    key: ${CACHE_KEY}
    policy: pull
    paths:
      - quality/node_modules/
  before_script:
    - if [ "$(docker ps -aq --filter name=^fc |wc -l) -ge 1" ]; then docker container rm -f $(docker ps -aq --filter name=^fc) || true; docker volume prune -f; fi
    - yarn config set proxy $PROXY_EXPLOITATION && yarn config set https-proxy $PROXY_EXPLOITATION
    - shopt -s expand_aliases
    - alias docker-stack=$FC_ROOT/fc/docker/docker-stack
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd $CI_PROJECT_DIR/quality/fcp && yarn install
    - cd $CI_PROJECT_DIR
  script:
  # Build the nginx proxy to access /integ01/fcp-low.html
    - docker-stack up rp-all
    - cd $CI_PROJECT_DIR/quality/fcp
    - yarn test:low:ci -c video=${CYPRESS_VIDEO} || RETURN_CODE=1
    - yarn report
    - exit $RETURN_CODE
  dependencies: []
  artifacts:
    expire_in: 1 hrs
    when: always
    paths:
      - quality/fcp/cypress/reports/cucumber/html-report
