test/shared:
  stage: test
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  tags:
    - node
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "staging"' 
  needs:
    - job: global-install
      artifacts: true
  script:
    - cd shared
    - yarn test
  interruptible: true
