test/shared:
  stage: Code quality
  image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
  tags:
    - node
  needs:
    - job: global-install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "fca-staging"'
  cache:
    key: '${CACHE_KEY}'
    policy: pull
    paths:
      - node_modules
      - fc-exploitation/node_modules
      - shared/node_modules
  script:
    - cd shared
    - yarn install
    - yarn test
  interruptible: true
