test/shared:
  stage: test
  image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
  tags:
    - nodejs
  needs:
    - job: global-install
      artifacts: true
  script:
    - cd shared
    - yarn test
  interruptible: true
