####################
####################
services:
  ####################
  # Base Services
  ####################

  base-nodejs:
    build:
      context: "../../../back"
      target: dev
    user: ${CURRENT_UID}
    tty: true
    networks:
      - fc
      - public
      - data
    init: true

  base-core:
    extends: base-nodejs
    depends_on:
      rp-all:
        condition: service_started
      maildev:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis-pwd:
        condition: service_healthy
    pre_start:
      - command: yarn run migrate up
      - command: yarn run seed
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO",
          "/dev/null",
          "--no-check-certificate",
          "https://localhost:3000/api/v2/readyz?exclude=api-entreprise,hyyyperbridge",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - "../../../back/apps:/var/www/app/apps:ro"
      - "../../../back/libs:/var/www/app/libs:ro"
      - "../../volumes/app:/opt/scripts"
      - "../../volumes/log:/var/log/app"
      - "../../volumes/.home:/home"
      - "../../volumes/ssl:/etc/ssl/docker_host:ro"
    tmpfs:
      - /var/www/app/dist:mode=777
    networks:
      - fc
      - public
      - data

  base-mock:
    build:
      context: "../../../back"
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      rp-all:
        condition: service_started
    tty: true
    init: true
    volumes:
      - "../../../back/apps:/var/www/app/apps:ro"
      - "../../../back/libs:/var/www/app/libs:ro"
    tmpfs:
      - /var/www/app/dist:mode=777

  base-mock-service-provider:
    build:
      context: "../../../mock-service-provider"
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      rp-all:
        condition: service_started
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "-qO"
        - "/dev/null"
        - "http://localhost:3000/readyz"
      interval: 1s
      retries: 2
      start_period: 1s
      timeout: 1s
    init: true
    tty: true
    volumes:
      - "../../../mock-service-provider/src:/var/www/app/src:ro"
      - "../../volumes/ssl:/etc/ssl/docker_host:ro"
    networks:
      - public

  base-mock-identity-provider:
    build:
      context: "../../../mock-identity-provider"
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      rp-all:
        condition: service_started
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "-qO"
        - "/dev/null"
        - "http://localhost:3000/readyz"
    tty: true
    init: true
    volumes:
      - "../../../mock-identity-provider/src:/var/www/app/src:ro"
    networks:
      - public

  base-mock-data-provider:
    build:
      context: "../../../mock-data-provider"
      target: dev
    user: ${CURRENT_UID}
    depends_on:
      rp-all:
        condition: service_started
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "-qO"
        - "/dev/null"
        - "http://localhost:3000/readyz"
      interval: 1s
      retries: 2
      start_period: 1s
      timeout: 1s
    init: true
    tty: true
    volumes:
      - "../../../mock-data-provider/src:/var/www/app/src:ro"
      - "../../volumes/ssl:/etc/ssl/docker_host:ro"
    networks:
      - public

  base-redis:
    image: "bitnamilegacy/redis:8.0.3"
    env_file:
      - ../shared/.env/redis.env
    healthcheck:
      interval: 2s
      start_period: 5s
    networks:
      - data

  ####################
  # Shared Services
  ####################

  rp-all:
    image: nginx:1.31.3
    container_name: pc-rp-all
    environment:
      DHPARAM_GENERATION: "false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../volumes/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../volumes/nginx-proxy/etc:/etc/nginx/conf.d:ro
      - ../../volumes/nginx-proxy/includes:/etc/nginx/includes:ro
      - ../../volumes/nginx-proxy/default-vhost:/etc/nginx/html:ro
      - ../../volumes/ssl:/etc/nginx/docker_host:ro
      - ../../volumes/ssl:/etc/nginx/client_certs:ro
      - ../../volumes/log/nginx:/var/log/nginx
    networks:
      public:
        aliases:
          # FCA LOW
          - federation-local.proconnect.127.0.0.1.nip.io
          - bridge-proxy-rie-local.proconnect.127.0.0.1.nip.io
          - front-local.proconnect.127.0.0.1.nip.io
          - sp1-local.proconnect.127.0.0.1.nip.io
          - sp2-local.proconnect.127.0.0.1.nip.io
          - sp3-local.proconnect.127.0.0.1.nip.io
          - idp1-local.proconnect.127.0.0.1.nip.io
          - idp2-local.proconnect.127.0.0.1.nip.io
          - moncomptepro-local.proconnect.127.0.0.1.nip.io
          # Aliases to access exploitation from test runner
          # TODO: Move those aliases to exploitation network once runner workaround found
          - admin-local.proconnect.127.0.0.1.nip.io
          - admin-high-local.proconnect.127.0.0.1.nip.io
          # Mock Data Provider
          - dpa1-local.proconnect.127.0.0.1.nip.io
          - dpa2-local.proconnect.127.0.0.1.nip.io
          # Generic
          - proconnect.127.0.0.1.nip.io
      fc:
      rie:
        aliases:
          - auth.llng-local.proconnect.127.0.0.1.nip.io
          - idp-rie-local.proconnect.127.0.0.1.nip.io
      exploitation:

  squid:
    image: ubuntu/squid:6.6-24.04_beta
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    extra_hosts:
      - auth.llng-local.proconnect.127.0.0.1.nip.io:172.16.1.254
      - idp-rie-local.proconnect.127.0.0.1.nip.io:172.16.1.254
    networks:
      - public
      - fc
      - exploitation
      - rie
    stop_signal: SIGKILL
    healthcheck:
      test: ["CMD", "bash", "-c", "echo >/dev/tcp/localhost/3128 || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 2
      start_period: 1s

  broker:
    build:
      context: "../.."
      dockerfile: "builds/broker/Dockerfile"
    # Specify hostname to fix cluster name
    hostname: broker
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data
    ports:
      - "5672:5672"
      - "15672:15672"

  ####################
  # Data storage
  ####################

  redis-pwd:
    extends: base-redis
    healthcheck:
      test: redis-cli -a $${REDIS_PASSWORD} role | grep master
    networks:
      rie:
      data:
        ipv4_address: 172.16.4.105

  pg-admin:
    image: postgres:16
    environment:
      - "POSTGRES_DB=pg-db"
      - "POSTGRES_USER=pg-user"
      - "POSTGRES_PASSWORD=pg-password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg-user -d pg-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data

  mongo:
    image: mongo:8.2.12
    command:
      - "--keyFile"
      - /mongodb-keyfile
      - "--replSet"
      - rs0
    env_file:
      - ".env/mongo.env"
    volumes:
      - "../../volumes/mongo/initdb.d:/docker-entrypoint-initdb.d"
      - "../../volumes/mongo-fca-low/scripts:/opt/scripts"
    post_start:
      - command: >
          sh -c "
            if [ ! -f /mongodb-keyfile ]; then
              openssl rand -base64 756 > /mongodb-keyfile &&
              chmod 400 /mongodb-keyfile &&
              chown mongodb:mongodb /mongodb-keyfile
            fi
          "
    healthcheck:
      test: 'test $$(mongosh --host $${HOSTNAME} -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --quiet --eval "try{rs.initiate()}catch(e){} ; rs.status().ok") -eq 1'
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    networks:
      - data

  ####################
  # Shared Mocks
  ####################

  openldap:
    image: osixia/openldap:1.5.0
    networks:
      - rie
    ports:
      - "5432:5432"

  maildev:
    hostname: maildev
    image: maildev/maildev:2.2.1
    networks:
      - data
      - public

####################
# Networks
####################

networks:
  public:
    ipam:
      config:
        - subnet: 172.16.1.0/24
  fc:
    ipam:
      config:
        - subnet: 172.16.2.0/24
  exploitation:
    ipam:
      config:
        - subnet: 172.16.3.0/24
  data:
    ipam:
      config:
        - subnet: 172.16.4.0/24
  rie:
    ipam:
      config:
        - subnet: 172.16.6.0/24
