services:
  partners:
    image: alpine
    depends_on:
      - "partners-front"
      - "partners-back"
      - "mock-proconnect"

  bdd-partners:
    image: alpine
    depends_on:
      # -- PARTNERS
      - "partners"
