services:
  partners:
    image: alpine
    depends_on:
      - "partners-front"
      - "partners-back"
      - "mock-proconnect"
      - "csmr-config-sandbox-low"
      - "csmr-config-partners"

  bdd-partners:
    image: alpine
    depends_on:
      # -- PARTNERS
      - "partners"
