####################
####################
services:
  exploitation-high:
    hostname: exploitation-high
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app/fc-exploitation
    depends_on:
      - "pg-exploitation-high"
      - "mongo-fcp-high"
      - "squid"
      - "mock-rnipp"
      - "broker"
      - "csmr-hsm"
      - "haproxy"
    volumes:
      - "${VOLUMES_DIR}/src/fc-apps:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/fc-apps/insee-db:/usr/share/insee-db"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/shared/.env/fc-mongo.env"
      - "${COMPOSE_DIR}/fcp-high/.env/exploitation-high.env"
    networks:
      - exploitation
      - data
    init: true
    command: "tail -f /dev/null"
