version: "3.4"

####################
####################
services:
  exploit-fcp:
    hostname: exploit-fcp
    image: gitlab.dev-franceconnect.fr:5005/france-connect/infra/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      - "pg-exploitation-high"
      - "mongo-fcp-high"
      - "squid"
      - "rnipp"
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/shared/.env/postgres.env"
      - "${COMPOSE_DIR}/shared/.env/fc-mongo.env"
    ports:
      - 9247:9247
    env_file:
      - "${COMPOSE_DIR}/fcp-high/.env/exploit-fcp.env"
    networks:
      - exploitation
      - data
    command: "tail -f /dev/null"
