version: '2.4'

####################
####################
services:
  mongo-fcp-high:
    hostname: mongo-fcp-high
    build:
      context: "${WORKING_DIR}"
      dockerfile: "${WORKING_DIR}/builds/mongodb/Dockerfile"
      args:
        MONGO_VERSION: "4.4"
    volumes:
      - "${VOLUMES_DIR}/mongo-fcp-high/scripts:/opt/scripts"
      - "${VOLUMES_DIR}/mongo-fcp-high/initdb.d:/docker-entrypoint-initdb.d"
    env_file:
      - "${COMPOSE_DIR}/fcp-high/.env/mongo.env"
    ports:
      - "27018:27017"
    networks:
      - data
