version: "2.4"

####################
####################
services:
  min-fcp-high:
    image: alpine
    depends_on:
      - "core-fcp-high"
      - "fsp1-high"
      - "fip1-high"
      # --
      - "rnipp"
      - "csmr-hsm"
      - "dp1-high"

  bdd-fcp-high:
    image: alpine
    depends_on:
      - "core-fcp-high"
      - "csmr-hsm"
      - "rnipp"
      - "exploitation-high"
      # -- SP
      - "fsp1-high"
      - "fsp2-high"
      - "fsp3-high"
      - "fsp5-high"
      - "fsp6-high"
      # -- IdP
      - "fip1-high"
      - "fip2-high"
      - "fip13-high"
      - "fip14-high"
      - "fip15-high"
      - "fip16-high"
      - "fip17-high"
      - "fip18-high"
      - "fip19-high"
      - "fip20-high"
      # -- DP
      - "dp1-high"
      - "dp2-high"
      # -- Mailer
      - "maildev"

  all-fcp-high:
    image: alpine
    depends_on:
      - "core-fcp-high"
      - "exploitation-high"
      # -- SP
      - "fsp1-high"
      - "fsp2-high"
      - "fsp3-high"
      - "fsp5-high"
      - "fsp6-high"
      # -- IdP
      - "fip1-high"
      - "fip2-high"
      - "fip6-high"
      - "fip13-high"
      - "fip14-high"
      - "fip15-high"
      - "fip16-high"
      - "fip17-high"
      - "fip18-high"
      - "fip19-high"
      - "fip20-high"
      # --
      - "rnipp"
      - "csmr-hsm"
      # --
      - "maildev"
      - "dp1-high"
      - "dp2-high"
