FROM python:3.13.2-slim

WORKDIR /var/www/app

# Get prypoject.toml from context
COPY pyproject.toml .

# Install dependencies
RUN pip install .

# Copy source code
COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]