name: 🐳 Build federation-admin docker image

on:
  push:
    # tags:
    #   - '*'

jobs:
  build_docker:
    name: 🐳 Build and register federation-admin docker image
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/admin
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ github.ref_name }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./admin
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/admin
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
