name: 💚 CI Tests - Federation Admin

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  global:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./admin/package.json

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Run coverage
        run: |
          yarn test --coverage
          ./node-scripts/coverage.sh

  unit-shared:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./admin/shared
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./admin/package.json

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  unit-exploitation:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./admin/fc-exploitation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./admin/package.json

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  e2e-exploitation:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dockerx
        uses: docker/setup-buildx-action@v2

      # Workaround for https://github.com/docker/compose/issues/12892
      - name: Upgrade Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set up Node.js for federation-admin
        uses: actions/setup-node@v3
        with:
          node-version-file: ./admin/package.json

      - name: Install dependencies
        working-directory: ./admin
        run: yarn install

      - name: Set FEDERATION_ROOT environment variable
        run: echo "FEDERATION_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Set PC_ROOT environment variable
        run: |
          PC_ROOT=$(dirname "$(pwd)")
          echo "PC_ROOT=$PC_ROOT" >> $GITHUB_ENV

      - name: Set ADMIN_ROOT environment variable
        working-directory: ./admin
        run: echo "ADMIN_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Create symlinks in federation
        working-directory: ./docker/volumes/src
        run: |
          ln -s "$FEDERATION_ROOT" federation
          ln -s "$ADMIN_ROOT" federation-admin

      - name: Start docker stack
        working-directory: ./docker
        run: |
          ./docker-stack prune-ci
          ./docker-stack up exploitation-fca-low
          ./docker-stack start-all-ci
          ./docker-stack wait "exploitation-fca-low" "https://exploitation-fca-low.docker.dev-franceconnect.fr/login" "240"

      - name: Start tests
        working-directory: ./admin
        run: yarn test:e2e:exploitation -c video=false

      - name: Post failing tests
        if: failure()
        run: |
          mkdir -p federation-admin/cypress/logs
          docker cp pc-exploitation-1:/tmp/.pm2/logs federation-admin/cypress/logs/fc-exploitation || true
          docker cp pc-rp-all:/var/log/nginx fc-exploitation/cypress/logs || true

      - name: Publish artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-outputs
          path: |
            fc-exploitation/cypress/screenshots
            fc-exploitation/cypress/videos
            fc-exploitation/cypress/logs
