name: 💚 CI Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test_static_back:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-node-modules-back-${{ hashFiles('back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-back-
      - name: Install dependencies
        working-directory: ./back
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress
      - name: Check doc
        working-directory: ./back
        run: |
          yarn doc
          git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)
      - name: Check code style
        working-directory: ./back
        run: |
          yarn lint
          yarn prettier
      - name: Check transpilation
          yarn tsc --noEmit

  test_static_quality:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: quality/node_modules
          key: ${{ runner.os }}-node-modules-quality-${{ hashFiles('quality/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-quality-
      - name: Install dependencies and run linting
        working-directory: ./quality
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress
      - name: Check code style
        working-directory: ./quality
        run: |
          yarn lint
          yarn prettier
      - name: Check transpilation
          yarn tsc --noEmit
