name: 💚 CI Tests

on:
  push:

jobs:
  test_static_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./back/package.json

      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check doc
        run: |
          yarn doc
          git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)

      - name: Check code style
        run: |
          yarn lint
          yarn prettier

      - name: Check transpilation
        run: yarn tsc --noEmit

  test_static_quality:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./back/package.json

      - name: Install quality dependencies
        run: yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check code style
        run: |
          yarn lint
          yarn prettier
      - name: Check transpilation
        run: yarn tsc --noEmit

  test_unit_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./back/package.json

      - name: Install dependencies
        run: yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Test code coverage
        run: yarn test --coverage

  test_snapshot:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality/fca
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dockerx
        uses: docker/setup-buildx-action@v3

      # Workaround for https://github.com/docker/compose/issues/12892
      - name: Upgrade Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set FEDERATION_ROOT environment variable
        working-directory: ./
        run: echo "FEDERATION_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Connect to docker registry
        working-directory: ./docker
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create symlink to federation root
        working-directory: ./docker/volumes/src
        run: |
          set -x
          ln -s $FEDERATION_ROOT

      - name: Start docker stack
        working-directory: ./docker
        run: |
          set -x
          ./docker-stack prune-ci
          ./docker-stack up small
          ./docker-stack start-all-ci

      - name: Install quality dependencies
        run: yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Test snapshots
        working-directory: ./quality/fca
        run: |
          yarn test:low:snapshot -c video=false
          yarn report

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-snapshots-artifacts
          path: |
            quality/fca/cypress/reports/cucumber/html-report
            quality/fca/cypress/snapshots/diff
            artifacts-logs

  test_e2e:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality/fca
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dockerx
        uses: docker/setup-buildx-action@v3

      # Workaround for https://github.com/docker/compose/issues/12892
      - name: Upgrade Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set FEDERATION_ROOT environment variable
        working-directory: ./
        run: echo "FEDERATION_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Connect to docker registry
        working-directory: ./docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create symlink to federation root
        working-directory: ./docker/volumes/src
        run: |
          set -x
          ln -s $FEDERATION_ROOT

      - name: Clone federation-admin repository
        uses: actions/checkout@v4
        with:
          repository: proconnect-gouv/federation-admin
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./docker/volumes/src/federation-admin

      - name: Start docker stack
        working-directory: ./docker
        run: |
          set -x
          ./docker-stack prune-ci
          ./docker-stack up medium
          ./docker-stack start-all-ci

      - name: Install quality dependencies
        run: yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Execute e2e tests
        working-directory: ./quality/fca
        run: |
          yarn test:low:chrome-desktop -c video=false --env TAGS="not @ignore"
          yarn report

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-e2e-artifacts
          path: |
            quality/fca/cypress/reports/cucumber/html-report
            quality/fca/cypress/snapshots/diff
            artifacts-logs
