name: 💚 CI Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-shared:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./shared
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./package.json

      - name: Cache Node.js dependencies
        id: shared-yarn-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-shared-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-shared-

      - name: Install dependencies
        if: steps.shared-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Run tests
        run: yarn test
  # unit-admin:
  # cypress:
  # snapshots:
