name: 💚 CI Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test_static_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: federation-yarn-cache
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-node-modules-back-${{ hashFiles('back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-back-

      - name: Install dependencies
        if: steps.federation-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check doc
        run: |
          yarn doc
          git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)

      - name: Check code style
        run: |
          yarn lint
          yarn prettier

      - name: Check transpilation
        run: |
          yarn tsc --noEmit

  test_static_quality:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: quality-yarn-cache
        uses: actions/cache@v3
        with:
          path: quality/node_modules
          key: ${{ runner.os }}-node-modules-quality-${{ hashFiles('quality/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-quality-

      - name: Install dependencies
        if: steps.quality-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check code style
        run: |
          yarn lint
          yarn prettier
      - name: Check transpilation
        run: |
          yarn tsc --noEmit

  test_unit_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: federation-yarn-cache
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-node-modules-back-${{ hashFiles('back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-back-

      - name: Install dependencies
        if: steps.federation-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Test code coverage
        run: |
          yarn test --coverage

  test_snapshot:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality/fca
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dockerx
        uses: docker/setup-buildx-action@v2

      - name: Start docker stack
        working-directory: ./docker
        run: |
          ./docker-stack prune-ci
          docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
          RETURN_CODE=0
          ln -s volumes/src/federation
          docker network create --driver bridge fc_public
          ./docker-stack up min-fca-low
          ./docker-stack start-all-ci

      - name: Test snapshots
        run: |
          yarn test:low:snapshot -c video=false
          yarn report

  # test_e2e:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
