name: 💚 CI Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  test_static_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: federation-yarn-cache
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-node-modules-back-${{ hashFiles('back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-back-

      - name: Install dependencies
        if: steps.federation-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check doc
        run: |
          yarn doc
          git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)

      - name: Check code style
        run: |
          yarn lint
          yarn prettier

      - name: Check transpilation
        run: |
          yarn tsc --noEmit

  test_static_quality:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: quality-yarn-cache
        uses: actions/cache@v3
        with:
          path: quality/node_modules
          key: ${{ runner.os }}-node-modules-quality-${{ hashFiles('quality/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-quality-

      - name: Install dependencies
        if: steps.quality-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Check code style
        run: |
          yarn lint
          yarn prettier
      - name: Check transpilation
        run: |
          yarn tsc --noEmit

  test_unit_back:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Cache Node.js dependencies
        id: federation-yarn-cache
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-node-modules-back-${{ hashFiles('back/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-back-

      - name: Install dependencies
        if: steps.federation-yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --ignore-engines --frozen-lockfile --no-progress

      - name: Test code coverage
        run: |
          yarn test --coverage
