name: ProConnect Federation CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  # Job for linting the back directory
  test_static_back_job:
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0
      - name: Install dependencies
        run: |
          cd back
          corepack enable
          corepack prepare --activate
          yarn install --ignore-engines --frozen-lockfile --no-progress
      - name: Run Linting
        run: |
          cd back
          yarn doc
          git --no-pager diff --exit-code || (echo "💥 You forgot documentation 💥" && exit 1)
          yarn lint
          yarn prettier
          yarn tsc --noEmit

  # Job for tag creation (testing in staging)
  test_staging_job:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Display Staging Test Log
        run: echo "Running tests for staging environment on tag creation..."

  # Job for tag creation (build images)
  build_job:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Display Build Log
        run: echo "Building images for tag creation..."
